### ISSUE TITLE
Translate the rules in fmc scramble

### ISSUE THREAD

**Issue by cs0x7f** [thewca/tnoodle#109]
https://github.com/cubing/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L496

These rules(or notice) are written in English, should we translate them into different languages?

**Comment by campos20** [comment]
I think it's a good time to implement this, since there was recent changes in the sheet [#231]. I'm a little concerned about verbose languages.

![captura de tela de 2016-12-23 00-07-37](https://cloud.githubusercontent.com/assets/10170850/21445743/f3c9832e-c8a3-11e6-84e4-05c33774a7a7.png)

**Comment by jfly** [comment]
Yeah, if we do this, we're probably going to have to write code that picks a font size based on what's necessary to make everyting fit in the available space.

**Comment by pepkin88** [comment]
Or just have a param with a font size assigned to each language, with a fallback to the default size. Should be easier to implement.

**Comment by jfly** [comment]
> Or just have a param with a font size assigned to each language, with a fallback to the default size. Should be easier to implement.

That sounds fine to me, since the content is static =)

**Comment by campos20** [comment]
I've been thinking about something like this, with internationalization.

Selection
![1](https://user-images.githubusercontent.com/10170850/28399481-aa745f3e-6ce3-11e7-8ba5-a448b6edaec8.png)

Options
![2](https://user-images.githubusercontent.com/10170850/28399499-bcce5180-6ce3-11e7-82e0-adc137e81795.png)

The file used in internationalization should be created, or at least updated, by some native speaker.

**Comment by jfly** [comment]
I'd rather generate every language every time, it's less work, and if people forget to set a language, or want to have multiple languages, we won't have any issues.

**Comment by campos20** [comment]
@jfly I'm not sure I'm following your thoughts. What do you mean by "generate every time"? The way I thought, all internationalization files should be included in tnoodle's files. The delegate sees like always, but the FMC sheet comes out in some specific language. If people forget to set language, I think English should be default. Anyways, I suppose at some point someone will have to translate. It could be

rule1 = Notate your solution...
rule2 = To delete...

in the corresponding language.

I must say that multiple languages it's something I did not consider before. Good point though!

**Comment by jfly** [comment]
Rather than generating just an English sheet, we could generate the sheet in every language we support.

**Comment by jfly** [comment]
By which I mean, if we support 3 languages, then we generate 3 different PDFs.

**Comment by campos20** [comment]
And the delegate just print the appropriate one. Got it now.

**Comment by campos20** [comment]
And the delegate just print the appropriate one. Got it now. It's a good idea.

Anyways, is it worth to start Internationalization, following your idea?

**Comment by jfly** [comment]
Sure! If you want to work on it, go for it!

**Comment by campos20** [comment]
I've just done a PR that I think fixes this.

Regular files remain intact, but the zip file has a new Internationalization folder, which contains a copy of FMC related sheets in every supported language.

![Uploading Captura de tela de 2017-11-10 18-09-27.png…](Regular files are still there)

![Uploading Captura de tela de 2017-11-10 18-09-32.png…](New folder with translated files)

If someone is wishing to translate, everything s/he has to do is to include a file with translated messages. No further coding will be required (counting on some minor changes by @jfly).

**Comment by campos20** [comment]
I've just done a PR that I think fixes this.

Regular files remain intact, but the zip file has a new Internationalization folder, which contains a copy of FMC related sheets in every supported language.

![captura de tela de 2017-11-10 18-09-27](https://user-images.githubusercontent.com/10170850/32678312-04e2ab88-c649-11e7-99f6-ec672714278b.png)

![captura de tela de 2017-11-10 18-09-32](https://user-images.githubusercontent.com/10170850/32678299-f59c58b8-c648-11e7-8bde-9e36a3e06543.png)

If someone is wishing to translate, everything s/he has to do is to include a file with translated messages. No further coding will be required (counting on some minor changes by @jfly).
