### ISSUE TITLE
scrambleviewer.html doesn't work without corresponding .jsonp file

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#164]
See https://github.com/cubing/tnoodle/blob/master/webscrambles/WebContent/wca/scrambleviewer.html and https://github.com/cubing/tnoodle/blob/b900d6e0595c6bdd787db2db100f091a41adc796/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L963.

We could embed the entire jsonp file into the html file, and then people would not need to extract the entire zip file in order to open the html file. This feels a little gross to me for some reason, but I can't put my finger on why. Is anyone opposed to doing this?

**Comment by gregorbg** [comment]
Closing this as outdated because we mainly rely on WCIF now.
