### ISSUE TITLE
Encoding JSON in URL

### ISSUE THREAD

**Issue by lgarron** [thewca/tnoodle#182]
Someone in https://news.ycombinator.com/item?id=9263834 linked to https://github.com/Nanonid/rison

**Comment by jfly** [comment]
Sweet! Rison sounds very similar to the hack we're doing in the url bar. It would be nice to use something standard. I don't feel too badly about breaking url compatibility across version of tnoodle if we're moving to something standard. Right now, CCM produces TNoodle links, and that required copying code out of tnoodle, which is a shame: https://github.com/cubing/ccm/blob/1be542ad64027408d55dd3472b3dc77779812968/client/components/tnoodleui.js

**Comment by suushiemaniac** [comment]
Closing this issue in favor of deprecating the Legacy UI
