### ISSUE TITLE
Don't squish scrambles on one line if it looks inconsistent.

### ISSUE THREAD

**Issue by lgarron** [thewca/tnoodle#186]
![screenshot 2015-03-29 21 11 22](https://cloud.githubusercontent.com/assets/248078/6890071/2bca7692-d658-11e4-9252-8630735e9baf.png)

TNoodle looks like it's being inconsistent and malfunctioning, which detracts from the "It Just Works" appeal.

If they encounter this, I think a lot of scramblers will at least ask _why_ this happened. I think many of them will still be left with a tiny but uncomfortable feeling that something went wrong (even if some of them might not care, and maybe not even notice).

Can we at least prevent this from happening on 3x3x3?

**Comment by jfly** [comment]
Right now, we make an effort to ensure that all scrambles in a particular table are the same font size (that's what this whole [longest*Scramble](https://github.com/cubing/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L771) business is about). We don't make an effort to ensure that the font size is consistent across both tables. We have the start of such an infrastructure here https://github.com/cubing/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L566 with the dryRun stuff.

This should be a fun, single afternoon project.

**Comment by lgarron** [comment]
Same for highlighting.

![screenshot 2015-03-30 22 49 54](https://cloud.githubusercontent.com/assets/248078/6913033/1f28ed06-d72f-11e4-84ef-8236e383086b.png)

**Comment by campos20** [comment]
Hey @lgarron, do you think https://github.com/thewca/tnoodle/pull/500 also fixed this?

**Comment by suushiemaniac** [comment]
I'm not Lucas but I'm absolutely certain this was fixed in your recent PDF refactorings.
