### ISSUE TITLE
Allow clicking "Generate" before initialization is finished.

### ISSUE THREAD

**Issue by lgarron** [thewca/tnoodle#187]
i.e. "set and forget" rather than having to babysit a slow computer.

Requested by Artem Melikian

**Comment by gyroninja** [comment]
Would something that looked like [this](https://i.gyazo.com/93a48e2122116025ff5007de0f559ecf.png) be good?

**Comment by jfly** [comment]
The only babysitting is that the pdf/zip file generation is not instant, right?

I'd rather not change our UI at all, I think the right thing to do is to add more logic to the progress bar: we should be generating the zip/pdf asynchronously, and only presenting the scramble button to the user when we've finished that work.

**Comment by lgarron** [comment]
Note that browsers may block downloads that are not triggered by an immediately preceding user gesture.

**Comment by jfly** [comment]
That should be fine: with what I suggest, the download would still be triggered by the user pressing a button.

**Comment by suushiemaniac** [comment]
A similar workflow has been implemented in the [new WCIF-compliant UI](https://github.com/thewca/tnoodle/pull/532)
