### ISSUE TITLE
Clock scrambles contain moves that do nothing

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/tnoodle#190]
Some clock scrambles contain moves to be executed zero times (such as L0+) - could these be ommited? I think it's easier for the scramblers when there are fewer moves to look at.

**Comment by jfly** [comment]
Thanks for the report! @clementgallet implemented the clock scrambler, so I'm pretty unknowledgeable here. Does the current behavior make things more consistent?

**Comment by UnsolvedCypher** [comment]
Not as far as I can tell. It's comparable to having D D' in a 3x3 scramble - it's a move that does nothing.

**Comment by lgarron** [comment]
> I think it's easier for the scramblers when there are fewer moves to look at.

[citation needed] :-P

I'd like to know 1) if experienced clock competitors agree with this, and 2) if people who occasionally scramble clock agree with this.)

Clock scrambling has a consistent peg order (which maps each move to a consistent physical location of the scramble in the cell), so I would suspect that leaving one out might mess with peg habits. The current situation may not be optimal, but I'd like us to make sure we're moving to something better if we want to make a change like this.

**Comment by Mollerz** [comment]
I would prefer to leave the zeros in. Leaving them in definitely helps making sure they are right for the first couple of times one does the scramble. After one or two times doing the scramble you learn to skip the pins that are 0 anyway.

**Comment by jfly** [comment]
I'm convinced! Closing this issue.
