### ISSUE TITLE
Generate FMC image only sheet

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#204]
@jbcm627 did this by hand for US Nationals: it's sometime's expensive to print out color, so instead, print out a bunch of black and white FMC sheets, along with a page with a bunch of copies of the scramble and image that organizers can cut out in advance.

@KitClement just aksed for this.

**Comment by gyroninja** [comment]
You are looking for a way to have a sheet full of exclusively normal images (not black and white)?

**Comment by jbcm627** [comment]
For US2015, we printed the following solution sheets:
[FMC_solution_sheets.pdf](https://github.com/cubing/tnoodle/files/445327/FMC_solution_sheets.pdf)

And the following scramble sheets (with actual scrambles, of course):
[FMC_solution_sheets.pdf](https://github.com/cubing/tnoodle/files/445328/FMC_solution_sheets.pdf)

**Comment by jfly** [comment]
Closing! This was fixed in #224.
