### ISSUE TITLE
McAfee doesn't like TNoodle (on Windows 10)

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#211]
Christopher Chi ([2014CHIC01](https://www.worldcubeassociation.org/results/p.php?i=2014CHIC01)) was running into this. See error message here:
![image](https://cloud.githubusercontent.com/assets/277474/14660544/20985ce2-065b-11e6-8aca-d07031d86153.png)

McAfee seems to be getting in the way of tnoodle doing what it needs to do while starting up. This is the line of code that was failing: https://github.com/cubing/tnoodle/blob/c6c0f6650e10d4ae76467532deb19a2504de9b67/utils/src/net/gnehzr/tnoodle/utils/Utils.java#L221

**Comment by jfly** [comment]
If Christopher stops Mcafee, then TNoodle will be able to start up. After that point, thie tnoodle_resources directory exists, and TNoodle can happily start even with McAfee running.

**Comment by suushiemaniac** [comment]
Hrm, this sounds like a general problem with the assumption that TNoodle creates resource folders. The `0.16` releases will have this fixed as they access the resources directly from within the JAR.

However, the problem still persists for when handling pruning tables. I will eventually look into ways for Java to detect whether it may write folders or not, and then continue the program workflow accordingly.

**Comment by suushiemaniac** [comment]
As of version 1.0.0, we do not create folders to store resources or pruning tables anymore. Threrefor this issue is outdated and can be closed.
