### ISSUE TITLE
Include TNoodle version in FMC sheet

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#213]
We do this everywhere else, so for consistency, this would be nice to have.

**Comment by campos20** [comment]
Despite I [coded this](https://github.com/thewca/tnoodle/pull/231) a while ago, I'm against it right now. FMC sheets goes to competitors and it seems an unnecessary information. All the other sheets are restrict to a few staff members and it looks necessary for them.

**Comment by jfly** [comment]
Oh, lol wow. Yeah, I'm ok with removing it. We should have information about the version of TNoodle used from when the delegate submits scrambles, so if we ever need this information, it will be in our database anyways.

**Comment by campos20** [comment]
> Yeah, I'm ok with removing it.

I'm not sure if I understood this correctly. That code was not merged, so the only left action is to close this issue ☺

**Comment by jfly** [comment]
Ohh, yeah, let's close this issue, then!
