### ISSUE TITLE
Make Square-1 scrambles consistently end with a slash

### ISSUE THREAD

**Issue by coder13** [thewca/tnoodle#221]
At Atomic Cubing Sumer 2016, our scramblers were having trouble with the scrambles because they didn't notice some ended with a / and others didn't. I propose we make scrambles more consistent as in all of them ending with a /. I don't know myself how much of an issue this is, but we had a problem.

**Comment by Laura-O** [comment]
I can understand that one can miss the slash at the end. However, it's quite easy to identify that by comparing the scrambled puzzle with the images (especially the image of the middle slices).

I am also not completely sure if it's possible to change that without making scramble sequences significantly longer. Can you say something about that, @cs0x7f?

**Comment by jfly** [comment]
I agree with @Laura-O that scrambles should look at the images. I don't think it's worth the effort to change our solver so it always ends in a slash.
