### ISSUE TITLE
Add number of "Copies" for each round

### ISSUE THREAD

**Issue by Baiqiang** [thewca/tnoodle#227]
Imagine such a normal case: we have 6 scramblers in 3x3 first round (for 100 people) and 1 scrambler in 3x3 final round (for 12 people).
So 3 copies of scrambles for first round is required and only 1 copy for final round.
Can we add a number field that specifies the copies? Thus we can only print one copy of the whole PDF file instead of printing 3 copies for 3x3 1st round, 1 copy for 3x3 final and so on.
![add copies](https://cloud.githubusercontent.com/assets/2390434/20028782/cacf5e9c-a375-11e6-94ce-9459879fe637.png)

**Comment by jfly** [comment]
Sure, this sounds like a nice feature. Will accept PR =)

**Comment by Baiqiang** [comment]
@jfly, the screenshot is just what I want. I'm not able to implement this. Please someone else do this. XD

**Comment by jfly** [comment]
Sorry, @baiqiang, if you can want it, you're going to have to build it, or find someone else to do it. I will happily answer questions about tnoodle, but currently everyone on the wca software team has stuff to work on that I consider more important, sorry!

**Comment by Baiqiang** [comment]
@jfly, OK, I understand and will try it.

**Comment by jfly** [comment]
Sweet! Feel free to reach out to me on gchat or email if you have any questions. I will try to respond quickly.
