### ISSUE TITLE
Duplicate rounds and scrambles

### ISSUE THREAD

**Issue by Laura-O** [thewca/tnoodle#229]
As reported on the delegate list: ([wrc link](https://groups.google.com/d/msg/wca-wrc/6lyiYd-wFW4/d8adiPTHBAAJ) [delegates link](https://groups.google.com/d/msg/wca-delegates/pSILDbac1bs/PsgUPHDhBgAJ)) there is a bug which results in the generation of two identical rounds with identical scramble sequences:

- open TNoodle;
- it automatically brings a round of 3x3, so add another round for 3x3;
- click in the X box (in the right) to remove round 1;
- add another round for 3x3 and there will be 2 rounds named round 2;
- generate the scrambles and open both rounds pdfs to see that they are identical;

**Comment by andersonaap** [comment]
I did the test. Bug confirmed.

**Comment by campos20** [comment]
Is it a problem to replace [this line](https://github.com/thewca/tnoodle/blob/master/scrambler-interface/WebContent/scrambler-interface/js/ui.js#L990) with

> removeButton.addEventListener("click", removeLastRound.bind(null, eventID), false);

?

In this way, every time the user clicks to remove a round, the last round of that ID would be removed. To the user, it looks like if the actual round is being removed and all the rest is being renamed. Also, [this function](https://github.com/thewca/tnoodle/blob/master/scrambler-interface/WebContent/scrambler-interface/js/ui.js#L875) could be erased.

**Comment by jfly** [comment]
@campos20, that sounds like a good solution! Could you send in a PR with it, and we'll give it a test.

**Comment by campos20** [comment]
PR done. If the user customizes the round, like editing Groups, Copies, Extra Scrambles, the trick might be discovered, since this will always erase the last one.
