### ISSUE TITLE
Scramble cutout sheet should dynamically compute font size for scramble title

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#235]
![image](https://cloud.githubusercontent.com/assets/277474/26699534/1e0420e6-46cf-11e7-8569-c2efb0764961.png)

As you can see in the photo above, the scramble title "Scrambles for 2017-04-25 - 3x3x3: Fewest Moves Round 1 Group A - Scramble 1 of 3:" doesn't fit, whereas the scramble does. That's because the scramble font size is computed dynamically in `addFmcScrambleCutoutSheet` in webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java, but the font size for the scramble title is hard coded to 12. It also might help to split the scramble description onto multiple lines.

**Comment by jfly** [comment]
CC-ing @gyroninja, who added this feature in PR #224.

**Comment by gyroninja** [comment]
Relevant ![regular sheet](https://i.gyazo.com/4beb33c6dc8ab7cbab49b183fe166e52.png)

**Comment by campos20** [comment]
It looks easy enough. For regular sheet, as pointed by @gyroninja, this has been fixed in #242. I suppose I could add this as well for cutout sheet.

**Comment by campos20** [comment]
see 1be5db3

![captura de tela de 2017-11-26 16-19-47](https://user-images.githubusercontent.com/10170850/33243052-a9efab7a-d2c5-11e7-9970-ba6c2f652a4a.png)

and

![captura de tela de 2017-11-26 16-24-23](https://user-images.githubusercontent.com/10170850/33243089-4a6e0f56-d2c6-11e7-915f-27cebca06c39.png)
