### ISSUE TITLE
How to customize with adding more events?

### ISSUE THREAD

**Issue by Julio974** [thewca/tnoodle#239]
I'm not a good programmer, but I would like to be able to add different events to it. I don't use the github version, but the WCA direct download. Here are the 5 kinds of scrambles I'd like to add to Tnoodle:
1) Add events where just the name changes (2x2 blind, 2x2 oh, pyraminx bld...)
2) Add events where the name and image change (like for dino cube, just reusing skewb scramble but with different image)
3) Add events where the name, image, and scamble length change (like for kilominx, shorthening megaminx scramble, but still with a different image)
4) Add events where the name, the image and the scramble change (like for ivy cube)
5) Add FMC for other events, either already in Tnoodle (2x2 fmc) or added (dino cube fmc for example)

Thank you for any help!

**Comment by Laura-O** [comment]
I am not really sure what you are asking for. If you are asking for these changes to be implemented, this will never happen as TNoodle is the official WCA scramble program and therefore it supports only the official events.

So what do you want to do with these scrambles?
If you just want to have "official" scrambles for unofficial events, the easiest way for most of your tasks is to generate the equivalent scrambles and edit the PDFs.

**Comment by lgarron** [comment]
> I am not really sure what you are asking for. If you are asking for these changes to be implemented, this will never happen as TNoodle is the official WCA scramble program and therefore it supports only the official events.

I think we should qualify that. TNoodle contains a timer and other unofficial parts. As long as the official parts are still reliable and easy to use, I don't see a problem with the project supporting unofficial events.

**Comment by Laura-O** [comment]
> I think we should qualify that. TNoodle contains a timer and other unofficial parts. As long as the official parts are still reliable and easy to use, I don't see a problem with the project supporting unofficial events.

Well, OK, that wasn't very precise: I doubt someone here volunteers to add several rare unofficial events and an additional user interface (which would be necessary as the current user interface is already quite overloaded).

If @Julio974 volunteers to do that, that's fine, but as he said he is not a good programmer, so I interpreted that rather as a request, not an intention.

**Comment by Julio974** [comment]
Even if the program is easy to use and edit, I'm very bad at programming. I don't ask for these changes to be implemented, just how I can make them

**Comment by Julio974** [comment]
But I can do the coding if it's not too complicated

**Comment by jfly** [comment]
> TNoodle contains a timer

That's actually not true, the timer was removed from TNoodle a while ago.

That said, I have always been supportive of adding unofficial events to TNoodle. As @Laura-O said, we're not going to be taking requests, but if someone from the community wants to add something, I would be glad to look over any PRs that people send in. @Julio974, if you're interested in sending a PR, please go for it! I am going to close this issue, however. We can continue the discussion over on any relevant PRs.

**Comment by Julio974** [comment]
I'm not asking to have this added to Tnoodle! I just ask how I can code it by myself!

**Comment by jfly** [comment]
That's great =) Do you have a specific question about how to get started? Are you able to `git clone` and compile TNoodle on your computer?

**Comment by Julio974** [comment]
I only downloaded the direct WCA link (https://www.worldcubeassociation.org/regulations/scrambles/), and I would just know how I can add scrambles to the version I downloaded

**Comment by jfly** [comment]
You won't be able to accomplish much with the download from the wca website. Try doing a git clone to get the code locally, and then follow the instructions from our readme (in particular, https://github.com/thewca/tnoodle/blob/master/README.md#wca-scramble-program-1)
