### ISSUE TITLE
generateScramble() not working

### ISSUE THREAD

**Issue by VershawnTan** [thewca/tnoodle#247]
I'm trying to build a very simple timer app with scramble, but the generateScramble() method keeps on crashing. am i doing it wrong?
The sample in the tnoodle-android doesn't work for whatever reason(don't know if it's intentionally or not)
`
    private void doScramble() {
        scrambleView.setText(R.string.scrambling);

        //problem at generateScramble()
        scrambleView.setText(cubePuzzle.generateScramble());
    }`

**Comment by jfly** [comment]
What's the error you're getting?

**Comment by VershawnTan** [comment]
Oh i forgotten to instantiate it. False alarm sorry.
