### ISSUE TITLE
Show summary of rounds and groups on the generate scrambles page

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#250]
@FatBoyXPC asked for this after taking a look at my changes in #236. Here's what it currently looks like:

![image](https://user-images.githubusercontent.com/277474/34274221-812d22f4-e64c-11e7-8838-52f06d9bdad4.png)

James suggests something like this:

![image](https://user-images.githubusercontent.com/277474/34274237-8efa15a4-e64c-11e7-8183-9ec99f7a95ac.png)

I'm creating this issue to start a discussion about this. Should we have a summary? If so, how should we represent it? In James's mock, I don't see the value of explicitly saying "group 1, group 2, group 3, ...". Could we just say "3 groups" instead?

**Comment by viroulep** [comment]
I couldn't help but notice the "# of copies" feature was not accessible through the new UI.

I personally don't use it but Delegates like @Baiqiang may want it to be still accessible.
Implementing this the way James suggests it would make it easy: just add an integer box next to the group and use this information to generate the scrambles :)

**Comment by FatBoyXPC** [comment]
Why do we need number of copies? That can be chosen when you print them!

I like seeing the break down so I can see at a glance how many groups are being generated per round. I suppose we could instead say

Event | Round | Groups
--|--|--
3x3x3 | Round 1 | 5 Groups
3x3x3 | Round 2 | 2 Groups
3x3x3 | Round 3 | 1 Group

I tried to leave out the last 2 usages of "3x3x3" but I was unable to make the table in doing so!

**Comment by jfly** [comment]
This is not going to make it in time for `v0.13.0`, so I'm removing it from the milestone.

**Comment by campos20** [comment]
![Captura de tela de 2019-07-27 20-22-34](https://user-images.githubusercontent.com/10170850/62000411-927c6480-b0ac-11e9-9eca-41d1b1dcb302.png)

Closing after 0.15

**Comment by jfly** [comment]
For the record, @campos20 implemented this in https://github.com/thewca/tnoodle/pull/402. Thanks, Alexandre!
