### ISSUE TITLE
FMC Sheet: "Competitor" and "WCA ID" aren't centered.

### ISSUE THREAD

**Issue by lgarron** [thewca/tnoodle#253]
<img width="374" alt="screen shot 2017-12-24 at 18 54 33" src="https://user-images.githubusercontent.com/248078/34331458-e5c04ec6-e8db-11e7-9e1b-d880cab47c5c.png">

**Comment by jfly** [comment]
@campos20, this would be a nice thing to take care of before the 0.13.0 release. Do you have any interest in taking a look? Thanks!

**Comment by campos20** [comment]
Sure! Just tell me about the deadline.

**Comment by jfly** [comment]
I'd like to send out a new beta of tnoodle for testing on Monday. Do you think you get work on this by then?

**Comment by leduyquang753** [comment]
I will work on it! :D

**Comment by campos20** [comment]
I believe we should close this after #386

**Comment by jfly** [comment]
I agree! Closing.
