### ISSUE TITLE
Implement a table layout for the new FMC sheet

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#255]
@lgarron introduced a table layout in #254, but it's just done with spaces right now. We want to investigate using a proper table, perhaps https://developers.itextpdf.com/examples/tables-itext5/101-very-simple-table is a good example to follow.

Examples of what we hope to achieve can be found here: https://github.com/thewca/wca-regulations/issues/456#issuecomment-320611555

**Comment by jfly** [comment]
@campos20, would you be interested in taking a look at this? Thanks!

**Comment by campos20** [comment]
Sure! I'll take a look.

**Comment by jfly** [comment]
(assigning to myself because I cannot assign to @campos20, but he'll be working on this!)

**Comment by campos20** [comment]
English

![captura de tela de 2018-01-04 00-05-00](https://user-images.githubusercontent.com/10170850/34547572-3d9cf248-f0e3-11e7-8186-23885a00a5ad.png)

Portuguese
![captura de tela de 2018-01-04 00-04-30](https://user-images.githubusercontent.com/10170850/34547579-490889a8-f0e3-11e7-9bf5-8992c78f36b7.png)

**Comment by jonatanklosko** [comment]
@campos20 could you include a screenshot for Polish (pl), please? The translation of clockwise and anti-clockwise is very long and I'd like to see how it looks =)

**Comment by jfly** [comment]
@campos20, could you actually include the screenshots in your PR #273?
