### ISSUE TITLE
Update outdated translations

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#265]
Here's the output of running [`./tmt i18n check`](https://travis-ci.org/thewca/tnoodle#L1603-L1757). We need to get these all fixed before releasing the next TNoodle.

```
> bundle exec wca_i18n webscrambles/src/i18n/en.yml webscrambles/src/i18n/*.yml
✔ da:	Up to date
✔ es:	Up to date
✔ et:	Up to date
✗ fi:	3 total = 1 missing + 1 outdated + 1 unused (https://github.com/thewca/tnoodle/pull/286)
✔ fr:	Up to date
✔ hr:	Up to date
✔ hu:	Up to date
✗ id:	3 total = 1 missing + 1 outdated + 1 unused (https://github.com/thewca/tnoodle/pull/304)
✔ ja:	Up to date
✔ ko:	Up to date
✗ nb:	3 total = 1 missing + 1 outdated + 1 unused (@jfly emailed Vidar and Ulrik requesting an update by Monday Jan 11th, 2018)
✔ pl:	Up to date
✔ pt:	Up to date
✗ pt-BR:	21 total = 0 missing + 21 outdated + 0 unused (@jfly emailed Pedro and Alexandr requesting an update by Monday Jan 11th, 2018)
✔ ru:	Up to date
✔ sl:	Up to date
✔ zh-CN:	Up to date
✔ zh-TW:	Up to date
```

**Comment by jfly** [comment]
It would probably also be nice to change Travis to run this hypothetical `check-i18n` script, so we can easily determine if the translations are up to date before releasing a new TNoodle.

**Comment by campos20** [comment]
@pedrosino said he was going to do some changes in my translation and I asked him to update directly to the yml. I'll update if he is too busy to do so, close to deadline.

**Comment by viroulep** [comment]
Thanks for the mention, I've updated the French translation in #270.

**Comment by viroulep** [comment]
As for the compare tool, we could use some python equivalent of [this](https://github.com/thewca/worldcubeassociation.org/blob/b98cc2c82afbf8dd2c80c64c2f42efd7d809822f/WcaOnRails/app/models/locale.rb#L86-L112)!

(we can even make it simpler, as we don't need pluralization things)

**Comment by jfly** [comment]
Instead of porting, how do you feel about pulling that code out into a rubygem that we could use from both TNoodle and the wca website?

**Comment by viroulep** [comment]
Yeah that would definitely work, as long as we provide an entry point that satisfies both app :)
(and assuming we can easily use Ruby stuff within tnoodle without too much changes)

**Comment by jfly** [comment]
I've started work on an external `i18n` Ruby tool here: https://github.com/thewca/wca-i18n. I basically have it working, but I still need to push to rubygems, and update TNoodle to use this new tool.

**Comment by jfly** [comment]
I added a `./tmt i18n check` command in #282.

**Comment by jfly** [comment]
As of #319, this is finally done!
