### ISSUE TITLE
Make the header, footer and the date format configurable

### ISSUE THREAD

**Issue by leduyquang753** [thewca/tnoodle#280]
Hi! Yesterday I have published a scramble document generated by Tnoodle-WCA for playing at school, so I gave the document to my friends, and they quickly realized that the header, footer and the date format were "odd":
* The page number that we familiar with is usually at the outer, bottom location of the page;
* The date format of ours is d/M/yyyy, so the date in the document (yyyy-MM-dd) was "completely ridiculous". And we thought it should be in the bottom too.

So, what we wanted was to make those things configurable by some ways (a file or a GUI), making it easier to read.
Thank you very much.

**Comment by lgarron** [comment]
I think we should avoid configuration that can result in contradictory formats.

As an alternative, how about we use the ISO 8601 yyyy-mm-dd format everywhere?

https://xkcd.com/1179/

I don't have strong opinions on where to put the page number, although i don't think it's an important enough detail to warrant a configuration option. Perhaps we should just go with what most books do?

**Comment by leduyquang753** [comment]
That ISO 8601 thing is not "everywhere".
And so as the page number: its most usual place in our books is in the outer, bottom. Here is an example: [Niên giám thống kê 2016 - Nông lâm ngư.pdf](https://github.com/thewca/tnoodle/files/1611489/Nien.giam.th.ng.ke.2016.-.Nong.lam.ng.pdf)
So, if you thought they were not neccesary to implement in TNoodle, it would be OK if you worked on the ability of building this on Windows, because I tried building it on my Windows 10 PC but the stuff went completely wrong with the **os.system** and **assert** things

**Comment by jfly** [comment]
I feel strongly about using YYYY-MM-DD everywhere, and not using any other kind of date formats.

I don't have strong opinions about where to put the page numbers, but I am not open to adding any configuration options to TNoodle, so any changes we make need to work for everyone.

@leduyquang753, I'm sorry that development on Windows doesn't work for you, I went to a lot of effort to support that initially, but it was just too much work to maintain. I highly recommend installing Linux or setting up a VM with Linux for TNoodle development.

**Comment by lgarron** [comment]
> I feel strongly about using YYYY-MM-DD everywhere, and not using any other kind of date formats.

Oh, I misread the initial report and thought it was saying that we were *not* using that. Sorry if my comments don't make sense.

**Comment by jfly** [comment]
Oh, no! You read the original post correctly. We were using yyyy/mm/dd in some places. I literally just fixed that in #288 (we now use yyyy-mm-dd everywhere).

**Comment by leduyquang753** [comment]
Oh no. Now I have to learn how to operate an entire new OS. I have just installed **VirtualBox** with **Damn Small Linux**, and yeah, things have been entirely new for me since then.
------------
**_I love Windows._**
