### ISSUE TITLE
Make the form's lines gray

### ISSUE THREAD

**Issue by leduyquang753** [thewca/tnoodle#307]
Hi! I saw in the FMC sheet, the form's lines is 100% black, and that can make the text written there harder to read. So I want to make these lines gray.
I am going to bundle this with **add-wca-id** pull request.
Thanks.

**Comment by campos20** [comment]
@leduyquang753 thanks for looking into this for us! I believe you could help in other open issues. For now, I'm suggesting this issue to be closed so we can focus on others. Thanks!
