### ISSUE TITLE
Use the same font size for translations in FMC sheet

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#312]
We are fitting each cell individually, which causes some texts to be smaller than others (as [pointed](https://github.com/thewca/tnoodle/pull/273#issuecomment-357099398) by @jonatanklosko).

![fontsize](https://user-images.githubusercontent.com/10170850/34854357-6dd8ea28-f720-11e7-93b5-41ea36dddc89.png)

To fix this, we can previously compute the font sizes and pick the smaller.

**Comment by campos20** [comment]
Relevant code.

https://github.com/thewca/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L712

**Comment by jfly** [comment]
I've added this to the 0.13.0 milestone for now, hopefully @campos20 can get this fixed before we release next week =)

**Comment by leduyquang753** [comment]
Hey! Can I add myself into the fun @campos20? ;D

**Comment by campos20** [comment]
> Hey! Can I add myself into the fun @campos20? ;D

It's great that we can count on you to help in the development! This part is already done in my computer, I just had to leave home before submitting. What about taking a look at some [other things](https://github.com/thewca/tnoodle/issues) to do? Welcome!
