### ISSUE TITLE
Margin for FMC sheet rules

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#315]
As [suggested](https://github.com/campos20/tnoodle/commit/47e46f56b68a2839c17e7aa592642c3e595306a2#commitcomment-26779950) by @lgarron, we could have nice margins for rules.

![Lucas' screenshot](https://user-images.githubusercontent.com/248078/34806052-e6a2593a-f635-11e7-9ca8-4b385becf4c0.png)

**Comment by campos20** [comment]
We might have to calculate the occupied width of the last column as well, to be super picky. For now, it's [fixed](https://github.com/thewca/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L672). When we ge there, some [other code](https://github.com/thewca/tnoodle/blob/master/webscrambles/src/net/gnehzr/tnoodle/server/webscrambles/ScrambleRequest.java#L752) will need to be updated.

**Comment by leduyquang753** [comment]
Will that look much more ugly? :confused:
