### ISSUE TITLE
How do I use tnoodle js?

### ISSUE THREAD

**Issue by cubetastic33** [thewca/tnoodle#330]
What function am I supposed to call to generate a scramble in tnoodle js?

**Comment by FatBoyXPC** [comment]
Please see [here](https://github.com/thewca/tnoodle#wca-scramble-program-1) for how to run the program :)

**Comment by cubetastic33** [comment]
@FatBoyXPC isn't that how you're supposed to run the JAVA files? I'm talking about the JavaScript one. Also, there seems to be two tnoodle.js files! Which one should I use?

**Comment by jfly** [comment]
Hey @cubetastic33, unfortunately there isn't much documentation around tnoodlejs. Your best bet is going to be to dive into the source code and start poking around. What are the two tnoodle.js files you're referring to?

**Comment by cubetastic33** [comment]
@jfly, there is one in the root directory, and one inside the tnoodlejs folder. And I don't seem to be able to understand the code, I would really appreciate it if any of you could tell me what to do! :smile:

**Comment by jfly** [comment]
@cubetastic33, in the future, it would be a lot easier for other people to help you out if you include links directly to the files you're talking about.

- https://github.com/thewca/tnoodle/blob/master/tnoodlejs/src/tnoodle.js#L1-L4 is a source file, you can see some comments on the top about what happens to it when we compile it
- https://github.com/thewca/tnoodle/blob/master/tnoodle.js is the compiled, ready to use tnoodle.js file. you should be able to import it and use it, but unfortunately the api is totally undocumented =(. You'll just have to poke around the tnoodlejs directory to figure stuff out: https://github.com/thewca/tnoodle/tree/master/tnoodlejs. I'm sorry, but I don't have the time to be more helpful than this right now.

**Comment by cubetastic33** [comment]
@jfly ok, I am trying to figure this out by myself, but a relative link at https://github.com/thewca/tnoodle/blob/master/tnoodlejs/demo.html is broken on line 12: `<script src="war/tnoodlejs/tnoodlejs.nocache.js"></script>`. No such file exists!

**Comment by cubetastic33** [comment]
@jfly nvm, I just experimented, and it looks like it meant <script src="../tnoodle.js"></script>, because when I did that, it seems to work! It successfully generated this for me: 
B' D B2 U R' B' D2 R' F' R' F' R2 L2 D2 F' R2 F' B2 R2
thanks a lot for your help!

**Comment by jfly** [comment]
Way to go!! Could you send in a PR fixing the bug you found in the demo file?

**Comment by cubetastic33** [comment]
@jfly sure, I am already working on that!

**Comment by cubetastic33** [comment]
@jfly ok, I'll make a pr tomorrow after adding some documentation to the JavaScript version, ok?

**Comment by jfly** [comment]
That sounds wonderful, thanks for taking the initiative here!

**Comment by cubetastic33** [comment]
@jfly well, I made a pull request, but it says that the Travis CI build failed, and from what I saw, it looks like there is some problem with the existing code that I didn't touch. So, please merge it if that is the case, or tell me what is wrong if that isn't the case!
