### ISSUE TITLE
Order scrambles by schedule

### ISSUE THREAD

**Issue by viroulep** [thewca/tnoodle#338]
Iskender commented that he could arrange the round order in the old ui to save the time needed to sort the printed sheets.
Once we'll have the schedule in the WCIF, we'll be able to add this neat feature without any additional input from the Delegate!

**Comment by Baiqiang** [comment]
With this https://github.com/thewca/worldcubeassociation.org/pull/3018 being merged, I think we can start to think how to solve this issue.

**Comment by jfly** [comment]
For the record, https://docs.google.com/document/d/19rxxUyu12noNhUnWfjhz1xZecsx68IIi-HV-jPjOK38/edit has some other proposals about making TNoodle "schedule aware".
