### ISSUE TITLE
TNoodle in python

### ISSUE THREAD

**Issue by cubetastic33** [thewca/tnoodle#339]
I want to use TNoodle in python. Is there any python version I could use? otherwise, is there any way to use the other code in python? Thanks!

**Comment by jfly** [comment]
@cubetastic33, TNoodle is written in Java, so it's not possible to run it in plain python. However, it is possible to use TNoodle through Jython! You can see us doing that in our `.jy` tests: https://github.com/thewca/tnoodle/tree/master/scrambles/test.

**Comment by cubetastic33** [comment]
@jfly cool! But, where are these imports from?

import tntdebug

from puzzle import TwoByTwoCubePuzzle
from puzzle import NoInspectionThreeByThreeCubePuzzle
from net.gnehzr.tnoodle.scrambles import AlgorithmBuilder

How do I install those modules (if required)?

**Comment by jfly** [comment]
tntdebug is here: https://github.com/thewca/tnoodle/blob/master/tntdebug.py

The other stuff is written in java. Jython let's you import java code, which is why this all works. You can find some more information about how exactly we invoke jython in this script: https://github.com/thewca/tnoodle/blob/master/jython.

**Comment by cubetastic33** [comment]
@jfly ok, but how do I execute this code? Like from my terminal? If I try jython *filename*, it obviously didn't work

**Comment by jfly** [comment]
Yes, from your terminal. If you have trouble with that, I suggest looking at what Travis does to run the tests (see https://github.com/thewca/tnoodle/blob/4f8781e40f005b5dc8cc79cb99dd6991d12b2ca0/.travis.yml#L25).

**Comment by cubetastic33** [comment]
@jfly I still don't understand. What command should I use?

**Comment by campos20** [comment]
Out of curiosity, what are you trying to do? I mean, generate scrambles? Are you writing a stand alone software?

**Comment by cubetastic33** [comment]
@campos20 well, I am trying to generate scrambles on my Raspberry Pi 0 W, and show them on an lcd screen.

**Comment by cubetastic33** [comment]
@jfly when I execute the command `./tmt make check`, it is giving a lot of logs, but how do I generate scrambles from a different python file? like, what function do I use?

**Comment by jfly** [comment]
@cubetastic33, I'd suggest reading our tests, it should be fairly obvious what's going on. Try taking a look at https://github.com/thewca/tnoodle/blob/master/scrambles/test/NoInspectionThreeByThreeTest.jy#L62.

**Comment by cubetastic33** [comment]
@jfly When I finished running it, this is what it said:

`BUILD FAILED

Total time: 11 mins 11.408 secs
Hit excepthook! stderr.isatty: True stdin.isatty: True stdout.isatty: True
Traceback (most recent call last):
  File "./tmt", line 1220, in <module>
    tmt._main()
  File "./tmt", line 231, in _main
    self.args.func()
  File "./tmt", line 287, in _make
    tmt._make(projectName=project.name, command='compile')
  File "./tmt", line 293, in _make
    commandFunc()
  File "tnoodle-android/tmtproject.py", line 17, in compile
    self.runGradleTask("assemble")
  File "tnoodle-android/tmtproject.py", line 14, in runGradleTask
    assert retVal == 0
AssertionError
> /home/pi/Desktop/tnoodle/tnoodle-android/tmtproject.py(14)runGradleTask()
-> assert retVal == 0`

**Comment by jfly** [comment]
What's the "it" that you ran? Is that the entire output?

**Comment by cubetastic33** [comment]
I ran `./tmt make check`again, and I got the following result:

$ ./tmt make check
svglite is up to date, not recompiling
utils is up to date, not recompiling
web-utils is up to date, not recompiling
winstone is up to date, not recompiling
sq12phase is up to date, not recompiling
min2phase is up to date, not recompiling
threephase is up to date, not recompiling
scrambles is up to date, not recompiling
Compiling: tnoodlejs/src
****************************************************************
Compiling java -> javascript using GWT. This is important to
test, as it can break easily, but it's also very slow, and
annoying for scrambler development. Set the TNOODLE_NO_GWT
environment variable to skip this.
****************************************************************
Could not find GWT at /home/pi/Desktop/tnoodle/tnoodlejs/gwt-2.5.1
You could visit https://developers.google.com/web-toolkit/download and install GWT yourself (be sure to set up a symlink from /home/pi/Desktop/tnoodle/tnoodlejs/gwt-2.5.1 to wherever you installed gwt.
Would you like me to download GWT and extract it to /home/pi/Desktop/tnoodle/tnoodlejs/gwt-2.5.1 for you? [y/n] y
Downloading: https://storage.googleapis.com/gwt-releases/gwt-2.5.1.zip Bytes: 111070580 to /tmp/tmpypb8aybi/gwt-2.5.1.zip
java -ea -classpath /home/pi/Desktop/tnoodle/tnoodlejs/gwt-2.5.1/*:lib/AppleJavaExtensions.jar:lib/gson-2.2.4.jar:lib/gwtexporter-2.5.0-SNAPSHOT.jar:lib/h2-1.3.169.jar:lib/javaee-api-6.0.jar:lib/jni-utils-1.1-SNAPSHOT.jar:lib/jopt-simple-3.2.jar:lib/markdownj-1.0.2b4-0.3.0.jar:lib/native-tray-adapter-1.2-SNAPSHOT.jar:lib/urlrewritefilter-5.0.0-SNAPSHOT.jar:min2phase/bin:min2phase/bin_tnoodle_resources:min2phase/src:scrambles/bin:scrambles/bin_tnoodle_resources:scrambles/postprocessed:scrambles/src:sq12phase/bin:sq12phase/bin_tnoodle_resources:sq12phase/src:svglite/bin:svglite/bin_tnoodle_resources:svglite/src:threephase/bin:threephase/bin_tnoodle_resources:threephase/src:tnoodlejs/bin:tnoodlejs/bin_tnoodle_resources:tnoodlejs/src:utils/bin:utils/bin_tnoodle_resources:utils/src:web-utils/bin:web-utils/bin_tnoodle_resources:web-utils/src:winstone/bin:winstone/bin_tnoodle_resources:winstone/src -Xmx512m com.google.gwt.dev.Compiler -strict -war tnoodlejs/war -style PRETTY scrambles
Feb 02, 2018 5:33:09 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Compiling module scrambles
Java HotSpot(TM) Client VM warning: INFO: os::commit_memory(0xab2a8000, 16953344, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 16953344 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/pi/Desktop/tnoodle/hs_err_pid3584.log
Hit excepthook! stderr.isatty: True stdin.isatty: True stdout.isatty: True
Traceback (most recent call last):
  File "./tmt", line 1220, in <module>
    tmt._main()
  File "./tmt", line 231, in _main
    self.args.func()
  File "./tmt", line 287, in _make
    tmt._make(projectName=project.name, command='compile')
  File "./tmt", line 293, in _make
    commandFunc()
  File "winstone/tmtproject.py", line 51, in newCompile
    if ogCompile(self):
  File "./tmt", line 938, in compile
    self._compile(self.src, self.bin)
  File "./tmt", line 1028, in _compile
    self.innerCompile(src, tempBin, bin)
  File "tnoodlejs/tmtproject.py", line 159, in innerCompile
    assert retVal == 0
AssertionError
> /home/pi/Desktop/tnoodle/tnoodlejs/tmtproject.py(159)innerCompile()
-> assert retVal == 0

**Comment by jfly** [comment]
For anyone else following along, we continued this discussion over on https://github.com/thewca/tnoodle/issues/341, for some reason...
