### ISSUE TITLE
Getting permission

### ISSUE THREAD

**Issue by VershawnTan** [thewca/tnoodle#346]
can i use the android version of tnoodle library to write a timer app to be posted on play store?

**Comment by jfly** [comment]
Hey @VershawnTan! Thank you for reaching out and asking about this. You can use TNoodle's Android library for your Android application. TNoodle is licensed under the [GPL-3.0](https://github.com/thewca/tnoodle/blob/master/LICENSE), which means you must also open source the code of your Android application under the GPL-3.0 if you want to use TNoodle.

When you've started working on your application, please reply here with a link to the Github repo of your project so we can confirm that you've done so. Thanks again!
