### ISSUE TITLE
Remove competition name from reusable FMC sheets

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/tnoodle#352]
When scrambles are provided separately, delegates can reuse FMC solution sheets across competitions (thus avoiding wasting unused ones). A simple solution would be to leave some space for competition name, as in the case of *round* and *attempt* number.

![image](https://user-images.githubusercontent.com/17034772/37254125-90a177a8-253a-11e8-9965-12fc2afd82ad.png)

**Comment by pedrosino** [comment]
+1

**Comment by campos20** [comment]
Interesting. I can work on that.

**Comment by campos20** [comment]
My first thought was to add "Competition: __________", but we'd have to ask translations for that.

![captura de tela de 2018-03-13 21-08-06](https://user-images.githubusercontent.com/10170850/37376401-de8cee38-2702-11e8-8d14-ea0c35d952da.png)

**Comment by jonatanklosko** [comment]
Good point, also competition names can be long on their own, so keeping just the name seems better. This looks great to me =)

**Comment by ronaldmansveld** [comment]
@campos20 I see you made changes for this issue on your fork, but there doesn't seem to be a Pull Request to merge this into TNoodle. Anything we can do to help if there's a reason for this?

**Comment by campos20** [comment]
> @campos20 I see you made changes for this issue on your fork, but there doesn't seem to be a Pull Request to merge this into TNoodle. Anything we can do to help if there's a reason for this?

My build is failing for some reason, so I can't really work on this until January. The code is already done, I just have to fix a few bugs (git related, I'm not really that comfortable with git). If you wanna work on this, go ahead!

**Comment by campos20** [comment]
All done.
