### ISSUE TITLE
Investigate crashing behavior

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#355]
Some [users reported](https://www.facebook.com/groups/cyoubxfriends/permalink/2154052454621196/) a crashing moments after TNoodle is opened,

![crashing](https://user-images.githubusercontent.com/10170850/37434556-b5b5a984-27be-11e8-9fb4-e44e3eb56ede.png)

**Comment by campos20** [comment]
Same as #336?

**Comment by jfly** [comment]
Sounds related! Thanks for looking into this.

**Comment by campos20** [comment]
It looks ok now, so I'm closing this.
