### ISSUE TITLE
Rename "Rubik's Clock" to "Clock"

### ISSUE THREAD

**Issue by KitClement** [thewca/tnoodle#359]
This event name in the legacy interface currently does not match the name we use on the WCA website.

**Comment by campos20** [comment]
Is here the only place you have noticed it?

![captura de tela de 2018-06-02 07-44-01](https://user-images.githubusercontent.com/10170850/40873559-e3495d1a-6638-11e8-8f9c-1d2420f45a8c.png)

**Comment by campos20** [comment]
It's already change, scheduled for the next release.

[Relevant code](https://github.com/thewca/tnoodle/blob/master/scrambler-interface/WebContent/scrambler-interface/js/ui.js#L364)
[PR](https://github.com/thewca/tnoodle/commit/9fffd5ed64ae4b7a28992fffd498143348192b1b)
