### ISSUE TITLE
Warning for rounds with one group

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/tnoodle#360]
The first time I used the new workflow (Login with WCA), I had not yet changed the group information in the WCA's site / manage events page. I ended up with a single group for every round and was confused. Later, @jfly informed me what I needed to do and it made more sense!

I figure some sort of warning before generating the scrambles if every round has a single group would be a nice mechanism to remind users when they are being dumb :smile:

**Comment by campos20** [comment]
Interesting. I suppose we could render the number of rounds and groups for each one.
