### ISSUE TITLE
MBLD input

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/tnoodle#361]
I personally feel like the MBLD input in the Login with WCA flow does not stand out enough. Maybe I'm a bad user, but I'm so used to the legacy UI's "Filename", "Password", "Scramble!" feel that I think when I saw this mbld input I assumed it wanted a file name and I was happy with the default.

I was at a competition where a competitor attempted 29 cubes rather than the current default of 28. This meant I had to do some manual json editing and it was a tad painful.

@jfly and I discussed several ways we could go about this. One way is that we could increase the default number by a multiple of 7 as people get better at mbld. I think another fun way could be to look at the current mbld record and get the next highest multiple of 7.

**Comment by ronaldmansveld** [comment]
As it seems that asking the delegate is now the behaviour of TNoodle after https://github.com/thewca/tnoodle/pull/362 instead of having a default , I think we can close this ticket?

**Comment by jfly** [comment]
Sounds good to me! Somewhat confusingly, #362 was closed without merging, but we did merge up 1 of the commits from it, specifically https://github.com/thewca/tnoodle/commit/1e37cec497024cbcf2abb397ff6807635b94a630
