### ISSUE TITLE
SecureRandom instead of Random

### ISSUE THREAD

**Issue by Eyremba** [thewca/tnoodle#364]
As far as I have seen using the GitHub search function, TNoodle uses java.util.Random nearly everywhere, but why not SecureRandom? On the normal random, there is a chance that the generated data has some repetitive patterns over time. Also, SecureRandom should be usable without any problems because it generates enough data for TNoodle.

**Comment by xsrvmy** [comment]
@Eyremba Actually I have been suspecting this is how the 19 FMC incident came about.

**Comment by jfly** [comment]
@Eyremba, where do you see plain Random being constructed? TNoodle definitely uses SecureRandom, although it's always possible there's a bug. See https://github.com/thewca/tnoodle/blob/1907465e421362d69b7bc2b3e0acb22437d7cee6/scrambles/src/net/gnehzr/tnoodle/scrambles/ScrambleCacher.java#L18-L22.

I'm going to close this issue, feel free to re-open if you think there's a bug here.

**Comment by Laura-O** [comment]
@xsrvmy Please stop posting this kind of suspicions.
You are obviously assuming that the delegate of the competition gave the TNoodle file to the competitor. Apart from the fact that this is the wrong place to discuss this, it's a really bad move to make up presumptions without having any background knowledge and post them publicly.

**Comment by xsrvmy** [comment]
Sorry about that. I deleted the comment. We probably misunderstood each other but I agree this is not a good place to talk about sensitive topics.

**Comment by Eyremba** [comment]
@jfly I meant, because in all puzzles, like for example the PyraminxPuzzle.java, it always imports the java.util.Random instead of the SecureRandom.

**Comment by jfly** [comment]
SecureRandom is a subclass of Random, isn't it? Do you see a plain old Random being constructed somewhere?
