### ISSUE TITLE
Investigate possible occurrence of invalid scramble moves

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#366]
This is the scramble generated for [Spring Cube In Minsk 2018](https://www.worldcubeassociation.org/competitions/SpringCubeInMinsk2018), 333, Round 1, Group H, Scramble 4, 

> F2 L2 U' R2 U' F2 U' F2 D2 F2 L2 F2 L' U B' D F' **K** B R2 B F2 U

Since K moves are not allowed for any event, we have to investigate this. Possibilities I considered so far are:

- Error on TNoodle (less likely, since this error would be more common)
- Human error while editing JSON (in that case, we should write some code to check before embedding on the oficial DB).

**Comment by campos20** [comment]
R1
['257940', 'BerkeleyWinter2016', '444', 'c', 'B', '0', '1', "R2 U' D' B2 L2 F2 L2 D' L2 B2 R D F' B L' F' B' D B' U Uw2 R1 B2 Uw2 F' B2 R U2 L' Uw2 Rw2 B' U' R' Uw' R' B Rw2 Fw L U Rw F' U'"] 

FW2
['257943', 'BerkeleyWinter2016', '444', 'c', 'B', '0', '4', "B' L2 F' B2 R2 F' B' D2 U' F' R B R' L' U F L U' Rw2 Uw2 D B2 D' Rw2 U Rw2 B' U D2 B' R2 Rw' FW2 F2 D2 F' Rw Fw' Rw' F B Rw2 U'"] 

2
B2 R2 D2 R F2 D2 L' R' B2 F' R' D2 F' L2 U' F2 R' 2 B' L2 Fw'
['661016', 'OficinaOpen2016', '333mbf', 'f', 'A', '0', '1', "R2 F2 D' R2 F2 U' L2 U L2 D L R' F R2 U' B2 R2 U B F2 U Rw Uw|F2 R2 D' B2 F2 D' F2 U' L2 F' R' D2 R2 U2 F' R' B' F2 D B' Uw2|B2 R2 D2 R F2 D2 L' R' B2 F' R' D2 F' L2 U' F2 R' 2 B' L2 Fw'|D U' R2 D2 L2 B2 R2 D L2 B F D' F2 U B' R2 B U R' U2 Rw' Uw2|R2 B' D2 R2 B' D2 U2 R B2 R D R2 B2 U' B2 L' B2 D2 Fw Uw'|F' L2 U2 F2 L2 D' R' F' D' B U' F2 U2 R B F Rw Uw2|D2 F L2 F2 U2 L2 F R' D' R' B2 D' U2 F2 R2 U L2 D Fw Uw2|D2 L2 U' L2 U R2 B2 U' F2 D F L B' U2 L2 D' F2 U' B' U2 L' Uw|L B2 R U2 R U2 L2 B2 U L' D2 F' L F' R2 B R D2 U Fw|U B2 F2 R2 D' R2 D' F2 U' R2 U' F R D L2 R' D' B F2 D B Rw2 Uw'|U2 R2 U' L2 D R2 U' R F U B U' F2 U R' F2 U L2 U2 Fw' Uw|U2 R2 B2 R2 B U2 F' U2 L2 U' F2 U2 R' D2 L U2 B' U2 F'|L U2 L D2 U2 R F2 L2 F2 U R2 B' U' L2 F R' U' L2 F' U2 Rw Uw|B' F' D2 F L2 R2 F' U2 R2 F R D' F U' B R D L2 B' D U2 Rw2 Uw2|F2 U L2 D2 L2 B2 D F2 U2 F' L2 D U2 R U R B2 U R U Rw2 Uw'|L2 B2 F2 D2 B2 L2 U' R2 U' B2 D' F' R' D' F2 D F' U' B D' Rw2 Uw2|F2 D2 F2 R2 U2 L2 D' F2 U F2 D' F R2 D L U R2 F U B' L Fw' Uw'|D2 F2 R2 B2 U2 F2 R B2 L2 B F2 U' R2 U' B' L2 U' F2 R' U' Fw|R2 U2 B' D2 B L2 F2 U' B2 D2 B' F2 U' R' U B F2 D Rw2 Uw2"] 

U'Rw
R2 D2 U2 B' R2 F' L2 B2 R2 U2 B2 U' B' R U' F' D' F' L' R' U'Rw Uw2 
['661411', 'ChachyaOpen2017', '333mbf', 'f', 'A', '0', '1', "R2 D2 U2 B' R2 F' L2 B2 R2 U2 B2 U' B' R U' F' D' F' L' R' U'Rw Uw2 |D2 R2 B R2 D2 F2 L2 R2 U' L U B' R' D2 R2 B2 R F2 D Fw |R2 F U2 F' D2 L2 D2 F2 U2 L U' R D2 F R D B U2 L2 Fw' Uw |F' L2 F D2 B R2 D2 B D2 L2 B2 D B' R' B2 L' B2 R2 U L2 B Rw2 |L2 F L2 F' L2 U2 B' F' U2 L2 D U B L' R' F U R B' U2 B Rw Uw |B2 R' U2 L' U2 R' B2 F2 R' F U' B' U L' B' R' F L2 R2 D2 Rw' Uw"] 

FwR
L U2 L B2 L B2 R' B R F' U R F2 D2 U' R F2 L FwR D2 F2 R B2 L F2 R' F2 L U' R' B' F2 U2 R2 F R' F Rw Uw'
['692241', 'PleaseBeQuietWPIWinter2018', '333mbf', 'f', 'A', '0', '3', "B2 L2 R' F2 D2 L2 F2 R' U' F' L B F' L' U R D F' R' Uw'|F2 R2 F' U2 B2 D2 B' L2 F L B F' D L' U' R B2 D2 L2 Fw' Uw|B' U2 L2 F' R2 B' R2 B L2 F2 D' R2 U' F D2 B' R F' D2 B2 Rw Uw|U' R2 D R2 F2 L2 D2 F2 D' F2 R B' U F2 U2 L2 B D2 R' D Rw Uw|L2 R2 U' B2 U B2 L2 R' F' D L' F' R' D' F2 L F' R F' Uw|R2 B2 D2 R2 D2 F2 U2 B' U2 F' D' F' R F' D2 R2 F L F2 L Fw'|D2 B2 R D2 U2 L' R D2 R2 B L' R' U' F' R D2 F' D2 L2 D' Rw'|U L2 B2 F2 U' L2 U F' L' R2 F2 U R' D2 B' L' U' B2 D Fw'|R2 F2 R2 U B2 L2 D U F' D2 R' B2 L' R' B R' D B2 D' R Uw2|L F2 L F2 L U2 B2 U2 L D' F L' R' F' U' L' U2 B2 L2 D' Rw|D2 F2 R2 D2 R2 U B2 D' R' F2 D B2 D' R' B U2 R B2 F D' Fw Uw'|F2 D2 U' B2 D2 U' L2 D' U2 L' B2 F R D L' D2 L U2 R2 Uw'|F2 D B2 D' F2 D' R2 D' R' B' L' U2 F' D L2 U B D L' U2 Fw'|L2 B2 D2 R2 U2 F2 R2 B F D B U' R' U' L U2 B2 F' R2 U Rw2 Uw2|F U2 F' U2 R2 B D2 L2 U2 L' U' F D' U' F' U2 L2 D' R2 D' Fw' Uw2|U R2 U B2 R2 D U2 R2 D2 U' L F' U2 L2 U R' U' F2 D' Rw Uw2|D' B2 R2 D2 B2 U' R2 B' R2 F2 D2 U' L' B' D B2 D2 U Rw' Uw'|F L2 R2 B2 U2 F' R2 F R2 U L R2 D' B' F D2 F L F' Rw2 Uw2|F' L2 B2 D2 U2 F' R2 D2 B2 F2 L' U' R D' U2 F R D2 R B F2 Uw|L2 F2 U2 L2 U2 L2 B D2 F2 L2 U B R F L2 R F L U R Fw Uw|D2 L2 B2 L2 B2 D B2 F2 D' L B D2 R F R D2 L2 B2 L U' F Rw Uw2|U2 L2 D2 R' F2 L U2 B2 U2 R' B' L U L D R U2 B L2 D' B' Rw' Uw2|B' U2 L2 F2 U2 R2 B' L2 B' R F L' B2 L B' R' U B2 L' B2 Uw|U B2 U' L2 R2 D' R2 U R B' F L B L B F2 L F L D' Rw2 Uw|U2 B2 L2 B2 U' F2 R2 D U2 R U R B' D' U2 L' R B2 U' F Rw Uw2|B R2 B L2 B F2 D2 B2 L2 U2 R' U' L' B D R' D U L2 B Uw|U F2 R2 F2 D2 L2 R2 F2 R' F2 R' F' L F L' U2 B2 U' R' Fw' Uw2|R' B2 D2 F2 U2 R2 D2 L B2 F' U F D B' R' D2 B' U' L U Fw|L2 B2 U2 L2 D2 L2 F' L2 U2 L' U B' L2 D R2 U' B' D2 R' B' Rw2 Uw|B' F D2 L2 B' L2 F2 L2 R2 U F R' B2 L' B L D2 L2 F R' Fw' Uw|F D2 B' L2 D2 F' L2 D2 L2 U2 F' R' D2 R U2 F' R2 U R F2 U Fw' Uw|B D2 R2 B2 R2 B' U2 L2 D2 B' L' U F2 D2 B' L F2 R F R Fw' Uw2|R2 B2 R2 B2 D' B2 F2 D' L2 B2 F' U' L F2 U2 B' U2 L' D B' D2 Fw' Uw|F2 D F2 U F2 R2 F2 D2 F2 D2 L D R' B D2 U B2 L D' F' R' Fw' Uw2|R' F2 D2 B2 L B2 R' F2 R B' F L' F R U F L D' B R Uw|L' U2 B R' U2 L' F2 B2 U R' B' R2 U2 F2 U2 B U2 D2 L2 B|L2 R2 F' L2 D2 R2 B U2 B R2 U' L F' L2 U2 R' F' L2 R2 B' Rw' Uw2|L2 R2 U' L2 D F2 D' U' R U R2 U F D' B U' R' F2 D' Rw2 Uw'|D' B2 L2 D B2 U' R2 F2 D L2 R' D' R D' R B F' R U' B F2 Uw|B R2 D2 L2 D2 R2 F2 D2 B F U' B D' B2 R' F D' R2 U2 L2 D2 Rw Uw|U2 R2 F2 L' U2 L2 R' D2 B L D' B' L B F2 D2 F2 L' D2 Fw' Uw|B F R2 U2 B' F2 D2 L2 F2 R2 F2 D' U' F' D R2 U L F2 U2 Fw'|L2 B2 D R2 F2 D2 U' F2 D B D' L' R U B2 D2 U' R Fw' Uw'|L2 U' L2 D B2 L2 D' U2 R2 F2 U2 L' B2 U2 B' U2 R' F U L' B' Uw|L U2 L B2 L B2 R' B R F' U R F2 D2 U' R F2 L FwR D2 F2 R B2 L F2 R' F2 L U' R' B' F2 U2 R2 F R' F Rw Uw'|F2 D' B2 U' F2 R2 D' R2 F2 U2 R2 B' L2 F' L2 U L' F' R D2 Fw Uw2|R D2 F2 L' F2 L' F2 U2 L2 U2 R D B2 L' B L B L2 F R2 F2 Rw'|R2 B' F R2 D2 U2 B U2 B2 L D2 B2 L' B' D' U L' B2 R F Uw'|R2 U2 L' U2 L' B2 L' R2 U2 B D B F2 U2 L' B2 F' U' F D Fw' Uw|B' D2 F' D2 F2 L2 R2 B' L2 B D2 U F2 L2 F' L B' U2 R D2 B' Rw2|D R2 D R2 F2 L2 B2 U2 B2 F U R2 B U L F2 L2 B' R F' Rw2|R2 U F2 R2 D' R2 D F2 U2 R2 U B' U' B R F D' F' D' L U Fw' Uw'|U2 F2 D2 F2 U2 R D2 L F2 R D L2 D' F U' L2 R2 U2 F L2 Fw|D' L2 B2 U B2 D L2 R' F' L R D2 F D' F' U2 F D Rw2 Uw'|D2 F2 D2 F2 R2 D' F2 R2 U2 F2 R2 B' D F U B2 F2 L D' B' D' Rw Uw|D2 U2 L U2 L2 F2 L' D2 R D2 R' F U' B2 L' B2 R2 F' D F U2 Fw Uw|B2 F2 L2 B2 D2 F2 R F2 L2 B' F' R' D2 U' L2 F2 L2 B' L Fw Uw|R2 B2 U' L2 U' B2 U F' D2 L R' U L U L' U2 F' R' U Rw' Uw2|U B2 F2 U' F2 D B2 L2 U2 B' R U2 F D' R U' F2 R' U2 F' D' Rw' Uw'|L2 R2 U2 B U2 B L2 D2 L2 D' R D L' B2 D U R B' L' U' Rw Uw'|B2 D U2 F2 U R2 F2 R2 D' U' L D R2 F U' B' R F D F' R Fw'|R2 U2 R2 B L2 B2 R2 D2 R2 D L' B D U2 B D' F' U' L D Fw' Uw|L2 D' L2 U' F2 U R2 D' R2 U' R' D F2 L' F' L2 F L B2 U' Fw' Uw2|R2 D2 R D2 B2 D2 R2 D2 R D2 L' F D U2 L' R2 D' R D' R2 D2 Fw' Uw'|B2 U2 L2 B F2 L2 F L2 U2 B' D2 L' D' U2 R U F U' B2 L U Rw2 Uw|L2 B' L2 U2 R2 F2 U2 B L2 R B' D R2 B' F' L' B R2 D2 L2 Fw Uw2|D2 F2 R B2 D2 L F2 U B' L2 B' R' D L2 D' B' F L2 Fw Uw2|D2 B' D2 B2 D2 F U2 R2 U2 B' D2 U R F' U2 L F R' U2 F' R2 Fw'|L2 D' R2 D' L2 R2 D' F2 U L2 U2 F' R D B D2 B D' L2 U Fw Uw'|U F2 L2 D' L2 R2 U2 R2 D2 L' U' R2 F D2 L2 D' R2 U2 L2 D2 Rw2 Uw'|F' U2 L2 D2 F' U2 B D2 B U2 F2 R' U' L R U B R B' L2 F' Rw2|B2 R2 F D2 B D2 B' L2 F2 L' D' L2 D2 B' D2 B L' U2 R' U2 Fw' Uw'|R' U2 L' U2 L B2 L' R2 U2 B' D2 U' L' U' B U2 L2 F2 D' R' Fw|F2 U F2 D2 R2 D2 R2 B' R B2 F2 U' F' L U' B L' U2 F' Rw|D2 R2 U2 B2 L D2 F2 R B2 D2 R2 U R2 D' F D R2 D' L F R Fw' Uw|F2 L2 U B2 L2 F2 U' B2 D U B' R' U2 F' D' R D' B R2 B Rw Uw'|F2 L B2 U2 B2 F2 L2 F2 U F R2 D2 U L' R' U2 F R2 Fw|D2 U2 R2 F2 L' U2 B2 R2 F2 U2 R B D' L' R D' L' B' U2 R' U Rw2|L2 U2 F2 L2 F' R2 F2 D2 U L' D R' U' B' U2 R2 D' B' U2 Fw' Uw2|L' D2 L B2 F2 L F2 L2 R' F U' R U2 L' B U2 B' L2 B' Rw Uw'|B2 U F2 U2 R2 D2 R2 D L2 B U L' B U2 L B2 U2 F2 R2 B Uw2|L2 U2 B2 U' B2 R2 D' F2 L2 R D2 B F' R' D' R' F2 U2 L' R2 U Rw Uw2|U R2 D2 B2 U' R2 U R2 B2 U2 B' F D' B2 R D' L' U' F' R' U2 Fw Uw2|U2 F' L2 B' R2 B2 F' L2 F' D' B' L2 R' U F D' F L2 F'|B2 D B2 F2 D2 R' D2 B' L' R' B R2 B2 R' B2 L U2 Fw' Uw'|L2 D2 B F D2 B' L2 F2 U F L D B R F R2 F2 D' U Fw'|R2 F2 D2 U2 R2 D' L' U2 L R2 F2 D' L' D U' L B U Rw2 Uw'|F2 D2 F2 U F2 L2 D' R2 U L' F2 L' U2 R' B' U' R2 D2 F2 D2 Rw Uw|F' R2 F L2 B' L2 F' D2 B' L2 U L2 U B U L2 R' U L B Rw|R D2 F2 R B2 L F2 R' F2 L U' R' B' F2 U2 R2 F R' F Rw Uw'|F2 D' B2 U' F2 R2 D' R2 F2 U2 R2 B' L2 F' L2 U L' F' R D2 Fw Uw2|R D2 F2 L' F2 L' F2 U2 L2 U2 R D B2 L' B L B L2 F R2 F2 Rw'|R2 B' F R2 D2 U2 B U2 B2 L D2 B2 L' B' D' U L' B2 R F Uw'|R2 U2 L' U2 L' B2 L' R2 U2 B D B F2 U2 L' B2 F' U' F D Fw' Uw|B' D2 F' D2 F2 L2 R2 B' L2 B D2 U F2 L2 F' L B' U2 R D2 B' Rw2|D R2 D R2 F2 L2 B2 U2 B2 F U R2 B U L F2 L2 B' R F' Rw2|R2 U F2 R2 D' R2 D F2 U2 R2 U B' U' B R F D' F' D' L U Fw' Uw'|U2 F2 D2 F2 U2 R D2 L F2 R D L2 D' F U' L2 R2 U2 F L2 Fw|D' L2 B2 U B2 D L2 R' F' L R D2 F D' F' U2 F D Rw2 Uw'|D2 F2 D2 F2 R2 D' F2 R2 U2 F2 R2 B' D F U B2 F2 L D' B' D' Rw Uw|D2 U2 L U2 L2 F2 L' D2 R D2 R' F U' B2 L' B2 R2 F' D F U2 Fw Uw|B2 F2 L2 B2 D2 F2 R F2 L2 B' F' R' D2 U' L2 F2 L2 B' L Fw Uw|R2 B2 U' L2 U' B2 U F' D2 L R' U L U L' U2 F' R' U Rw' Uw2|U B2 F2 U' F2 D B2 L2 U2 B' R U2 F D' R U' F2 R' U2 F' D' Rw' Uw'|L2 R2 U2 B U2 B L2 D2 L2 D' R D L' B2 D U R B' L' U' Rw Uw'|B2 D U2 F2 U R2 F2 R2 D' U' L D R2 F U' B' R F D F' R Fw'|R2 U2 R2 B L2 B2 R2 D2 R2 D L' B D U2 B D' F' U' L D Fw' Uw|L2 D' L2 U' F2 U R2 D' R2 U' R' D F2 L' F' L2 F L B2 U' Fw' Uw2|R2 D2 R D2 B2 D2 R2 D2 R D2 L' F D U2 L' R2 D' R D' R2 D2 Fw' Uw'|B2 U2 L2 B F2 L2 F L2 U2 B' D2 L' D' U2 R U F U' B2 L U Rw2 Uw|L2 B' L2 U2 R2 F2 U2 B L2 R B' D R2 B' F' L' B R2 D2 L2 Fw Uw2|D2 F2 R B2 D2 L F2 U B' L2 B' R' D L2 D' B' F L2 Fw Uw2|D2 B' D2 B2 D2 F U2 R2 U2 B' D2 U R F' U2 L F R' U2 F' R2 Fw'|L2 D' R2 D' L2 R2 D' F2 U L2 U2 F' R D B D2 B D' L2 U Fw Uw'|U F2 L2 D' L2 R2 U2 R2 D2 L' U' R2 F D2 L2 D' R2 U2 L2 D2 Rw2 Uw'|F' U2 L2 D2 F' U2 B D2 B U2 F2 R' U' L R U B R B' L2 F' Rw2|B2 R2 F D2 B D2 B' L2 F2 L' D' L2 D2 B' D2 B L' U2 R' U2 Fw' Uw'|R' U2 L'"] 

K
['741868', 'SpringCubeInMinsk2018', '333', '1', 'H', '0', '4', "F2 L2 U' R2 U' F2 U' F2 D2 F2 L2 F2 L' U B' D F' K B R2 B F2 U"] 

U2B
['741876', 'SpringCubeInMinsk2018', '333', '1', 'I', '0', '5', "D' L2 B2 L2 D' B2 L2 U B2 D' B2 L U2B R' F2 U2 L2 B U2 R"] 

B'D
['741878', 'SpringCubeInMinsk2018', '333', '1', 'I', '1', '2', "D' B2 U L2 D' U2 L2 F2 R2 F2 L D2 B'D U2 R B' L' R B'"] 

Rw'Uw2
U' F2 U2 B2 F2 L2 D B2 D F2 D' B R U F' D B' F L F D' Rw'Uw2
['797490', 'IbiOpen2018', '333mbf', 'f', 'A', '0', '1', "F2 R' D2 L D2 R B2 F2 R2 U' R F2 U L2 U2 B L2 R' F Rw' Uw2|B2 D F2 D R2 U2 B R2 D U2 B' L' D' L' R' F' U' R2 Fw Uw2|L2 D' U2 B2 L2 U' L2 D L D' R' B2 U B' L' F R' U2 B2 U2 Rw' Uw2|F' U2 B' L2 F' U2 B' R2 B' D2 F R B' L U R' B' F2 D2 B'|U' B2 F2 D' U' R2 U' R2 B' D L D B2 D' L' D2 U R2 F' Rw Uw|L2 R2 B2 U' F2 D2 L2 U' L2 U2 L D' F' L R U B L' R U2 L Fw|F R2 B R2 B2 R2 U2 B2 F L2 F2 L D2 B' F' L D' F2 R' D' R' Fw' Uw2|U' F2 D U F2 U' B2 L' F R' B L D' B' U2 R U B U Fw' Uw2|D2 F2 R2 D' U' R2 B2 L' F' U B' F' D' F U2 R2 F2 D F Uw'|L2 U' F2 U' L2 U2 R2 F2 D B' U' B2 U F' L D L' F2 L2 U' Rw' Uw2|R2 F D2 F2 R2 F D2 L2 D2 L2 D' R' D2 B2 R2 B F' R' F' U2 Rw' Uw|B2 U2 L R2 U2 B2 R2 F2 L F2 D L' B L2 F2 R B2 U' L2 B2 Rw Uw|L2 B2 F' L2 F' R2 U2 L' D2 U' B2 F2 R' F D2 L2 B R2 U' Rw2 Uw|D2 B2 U' B2 R2 D' U' F2 U F' D2 L' F2 D' B F2 L2 U' R' Fw Uw|D L2 R2 B2 D B2 U F2 D' L2 U F U2 R D' B F R' U L' B' Rw' Uw2|B F2 D2 B R2 D2 L2 F2 U' L2 D' U' L' U' L F R' B D Rw|L R U2 R' F2 D2 B2 D2 B' L R' D B F2 R' U' F' U F2 Rw' Uw|F2 U2 F2 D F2 R2 D F2 D' F2 L U2 L' U F D2 L B' R2 F Uw|B' U2 F2 D2 F' R2 D2 U2 B R' D' B' L' F D' L2 F' U L D2 Rw' Uw'|F D2 B' L2 F U2 F' L2 F' U L2 F' L' D' L' F' U L2 D2 R' Fw' Uw'|L2 R2 U R2 F2 U' B2 F2 D B' U R2 B F2 R B' D2 U' F2 R2 Fw Uw'|B2 L2 D2 U2 R F2 L D2 R2 D R U2 L' B2 L' R2 F D2 R' F Rw'|F2 D' L2 R2 U L2 U2 B' R F' D U2 R D U F2 L2 R' B' Rw2 Uw|U L2 U' B2 F2 D L2 B2 L2 F' L U B' D R2 D2 L R2 B U Rw2 Uw'|D2 L2 D2 B' L2 B' D2 F L' R2 D' B D' F2 L2 D2 B L' D F Rw2 Uw'|L R2 F2 L' F2 D2 B2 R2 F2 R' D' L' F R' F' U F2 L F2 U Fw' Uw'|B D2 L2 U2 B R2 F D2 F2 D2 R' F R2 D F2 R2 F R U' L' Fw' Uw|L2 R2 B U2 F L2 B D2 F2 U2 B D R B R' B2 L2 D' U' F' Rw' Uw2|U' F2 U2 B2 F2 L2 D B2 D F2 D' B R U F' D B' F L F D' Rw'Uw2"] 

RW'
['839788', 'ErciyesWeekend2018', '444', 'd', 'B', '0', '2', "B2 R2 D L' F R' F' U2 B' U' F2 D2 B L2 D2 R2 L2 F D2 R2 Fw2 Uw2 D Fw2 F' L2 B2 D B F2 Rw F' Rw2 R F' RW' L Uw Fw Uw2 F2 Uw L' Uw'"] 

Y
['839790', 'ErciyesWeekend2018', '444', 'd', 'B', '0', '4', "F R2 F2 D2 F' U2 L2 B' L' B' R2 B2 R2 Y D' F' L2 F2 D' Rw2 Fw2 U L' Uw2 Rw2 F2 L B2 L2 F2 U' L' F Rw2 Fw2 Rw2 U Fw' Uw' Rw' U2 R2 B2 Rw2 Fw2"] 

RW'
['839791', 'ErciyesWeekend2018', '444', 'd', 'B', '0', '5', "B2 F2 U2 B2 L B2 U B L' U' F R D' L D L2 R2 Rw2 D2 F' RW' R D2 Fw2 R' Uw2 B U2 F L' Uw R2 B2 U2 F U Fw D' R Uw' Rw' B L"] 

UW'
['839793', 'ErciyesWeekend2018', '444', 'd', 'B', '1', '2', "R' B2 R' F2 L B2 L U2 R2 U' F' L B R' D' U' L D B' D Rw2 D2 Fw2 B R' UW' F' L2 R Fw2 Uw2 R2 Uw' L' B U D2 B2 Rw' Uw' F2 Uw Fw' U' Fw"] 

fW2
['839795', 'ErciyesWeekend2018', '444', 'f', 'A', '0', '2', "U' R2 U2 B' R' F2 U2 L2 D' L F U L2 B2 D U B2 L2 B2 D' Rw2 F' R2 fW2 U2 R D2 Rw2 F Uw2 R B2 Uw' Rw2 U2 F' U' Fw2 U Fw Rw2 Uw2 Rw' F2"] 

rW2
['839796', 'ErciyesWeekend2018', '444', 'f', 'A', '0', '3', "L2 D2 L' D2 L' B2 R' F U L2 U' L2 U L' D2 R' D' F' Fw2 D2 rW2 L' D Fw2 U D' R B2 U' L Fw F Uw2 L Fw2 F2 Uw' Fw' D' Rw D' Fw2 F"] 

d2
['839798', 'ErciyesWeekend2018', '444', 'f', 'A', '0', '5', "D2 L' U2 R L B2 L D2 F2 d2 F2 L' D2 R B' U2 F2 L2 D' B Fw2 D2 L B' U2 Rw2 L' Uw2 L' Fw2 B' Uw' B' D' L B2 Rw2 Fw D' Rw F2 Rw2 F' R2"] 

UW
['839829', 'ErciyesWeekend2018', '555', 'c', 'A', '1', '2', "R' F' Rw2 D2 Fw U B2 R Bw F Lw U2 L2 Lw2 R Uw2 D' U Bw2 Fw' Rw B2 F' Fw' Bw R2 Fw Lw2 Dw2 Rw' UW D2 U2 Fw' F2 Dw F' D' L2 Fw Bw B Uw' R Rw' Lw' F2 B Bw L R F R Fw L' D2 Rw' D' R2 Fw"] 

BR'
['839836', 'ErciyesWeekend2018', '333oh', 'd', 'A', '1', '2', "U2 F2 L2 R2 U2 L2 R2 U L2 D B U' B2 U' L' D B' L BR'"] 

UL'
['839843', 'ErciyesWeekend2018', '333oh', 'd', 'B', '1', '2', "R B2 L2 R D2 B2 F2 L2 U L D2 L' U B D R' UL'"] 

U'R--
['839861', 'ErciyesWeekend2018', 'minx', 'c', 'B', '0', '4', "R-- D++ R++ D-- R-- D-- R++ D++ R-- D-- U' R++ D++ R-- D-- R-- D++ R++ D++ R++ D++ U R++ D++ R++ D-- R-- D-- R++ D++ R++ D++ U R-- D++ R++ D-- R++ D++ R-- D++ R++ D-- U' R-- D++ R-- D-- R-- D++ R++ D-- R-- D-- U' R-- D++ R++ D-- R++ D++ R++ D-- R-- D-- U'R-- D++ R-- D-- R-- D++ R++ D++ R++ D-- U'"]

**Comment by Jambrose777** [comment]
I'll look into these via WRT. My guess is that they are no fault of TNoodle, but rather delegate error.

**Comment by SAuroux** [comment]
@campos20 Thanks for this investigation. WRT is still chasing a few delegates, but most of these are fixed by now. 

Out of interest (and possibly for retesting): Would you be willing to share the code you used to find these?

**Comment by campos20** [comment]
It was some dirty code that kept adding exceptions to any new move. I checked them manually to validate, it took me about 10 min. I'm willing to write some more useful code that even matches the scramble with the event. Suggestions would be welcome.

**Comment by SAuroux** [comment]
@campos20 I decided to use this opportunity to practice regular expressions and came up with a script doing per-event checks myself: https://github.com/SAuroux/wca-analysis/blob/master/results-scripts/scramble_validity_analysis/scramble_validity_check.py

In any case: thanks again for bringing this topic up!

**Comment by campos20** [comment]
@SAuroux please include a length checker. I found MBLD scrambles whose length was 4. My suggestion is to calculate the average of all lengths (avg), the standard deviation (dev) and set an alarm for those that are out of the interval [avg-3.dev, avg+3.dev]. This is based on [Shewhart](https://www.spcforexcel.com/knowledge/control-chart-basics/three-sigma-limits-control-charts)'s work.

Your code is a bit messy to ready, but I'm sure you know what you are doing! I was about to consider dates as well. What if an event change its way of scramble? Like FMC.

**Comment by SAuroux** [comment]
> @SAuroux please include a length checker. [...]

The regular expressions already included length checks, min length checks for 3x3x3 and 4x4x4 and exact length checks for all other events where scramble length is fixed.
However, you motivated me to also include mx length checks for the 3x3x3 and 4x4x4 events, which indeed gave two new results!
I am familiar with outlier detection methods, but I am certain that fixed range checks are perfectly fine here. My rough guess is that my chosen ranges are even narrower than 3 sigmas anyway.
 
> Your code is a bit messy to ready, but I'm sure you know what you are doing! I was about to consider dates as well. What if an event change its way of scramble? Like FMC.

Uhm, thanks? :P 
I think that my code is very readable, but I assume that you are refering to the regular expressions? For those, there is simply no choice.
I have added support for R' U' F FMC scrambles (2017 and later), but this didn't give any additional errors.
