### ISSUE TITLE
Scrambling scape param

### ISSUE THREAD

**Issue by jdediegomrt** [thewca/tnoodle#373]
Working with tnoodle android library I have found an issue. 
In android library, for Android _cancel(**boolean** mayInterruptIfRunning)_ doesn't necessarily stop the execution of the scrambling process. The AsyncTask only executes onCancelled(), and won't run onPostExecute() when it completes.

for this reason if you try to cancel an scramble it wont be cancelled. 

This could be solved adding a scape flag or somenthing similar into scrambling loops. Something like:

In Puzzle.java

```
package net.gnehzr.tnoodle.scrambles;

//This variable is my example
   private boolean skipPuzzleScramble = false;
   /*Add get & set*/

```

...

```
    public final String generateWcaScramble(Random r) {
        PuzzleStateAndGenerator psag;
        do {
            psag = generateRandomMoves(r);
        } while(psag.state.solveIn(wcaMinScrambleDistance - 1) != null && !skipPuzzleScramble);
        return psag.generator;
    }
```

...

```
    @NoExport
    public PuzzleStateAndGenerator generateRandomMoves(Random r) {
        AlgorithmBuilder ab = new AlgorithmBuilder(this, MergingMode.NO_MERGING);

        while(ab.getTotalCost() < this.getRandomMoveCount()) {
            HashMap successors = ab.getState().getScrambleSuccessors();

            try {
                String move;
                do {
                    move = (String)GwtSafeUtils.choose(r, successors.keySet());
                    successors.remove(move);
                } while(ab.isRedundant(move) && !skipPuzzleScramble );

                ab.appendMove(move);
            } catch (InvalidMoveException var6) {
                l.log(Level.SEVERE, "", var6);
                GwtSafeUtils.azzert(false, var6);
                return null;
            }
        }

        return ab.getStateAndGenerator();
    }

```

A simple way to check this issue is:
in tnoodle android project launched,
scramble a Square-1 or a 4x4x4 and quickly scramble a 2x2x2 or a Skewb
You will see that it takes too much time to end a scramble that initially takes a few second to end.

do you see this issue?
is this a correct way to make it possible?

**Comment by jfly** [comment]
Ah, interesting! +@plusCubed to see if he has thought about this at all.

In general, there are a lot of places throughout TNoodle where we sit in a loop, CPU bound. It seems like a big pain to try to add "escape hatches" to each of them, and furthermore, to remember to add them to new places.

**Comment by suushiemaniac** [comment]
The suggestion to add boolean flags like your `skipPuzzleScramble` definitely feels wrong. In general, you should try to do the heavy lifting in separate threads. You could try marking them as `daemon` which [tells the JVM to shut them down](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#setDaemon-boolean-) if no reference is left.

Speaking of Android, even in an `AsnycTask` implementation you should wrap the scramble generation into some form of `Future` or `Promise` implementation (depending on what kind of parallelisation framework you're using). Then cancelling the AsyncTask will also cancel the underlying `Job` that is executed by a `Future` for example.

**Comment by suushiemaniac** [comment]
We also have [a class](https://github.com/thewca/tnoodle/blob/master/scrambles/src/main/java/net/gnehzr/tnoodle/scrambles/ScrambleCacher.java) called `ScrambleCacher` in the `scrambles` module that may help you getting the job done.

**Comment by suushiemaniac** [comment]
Closing this issue in favor of https://github.com/thewca/tnoodle/pull/474.

Please use the `ScrambleCacher` implementation for computation-heavy work and open a new issue if that approach somehow doesn't work out for you.
