### ISSUE TITLE
Duplicate MANIFEST.MF in "scrambles" dist

### ISSUE THREAD

**Issue by suushiemaniac** [thewca/tnoodle#376]
Version: checkout from https://github.com/thewca/tnoodle/commit/9cabf7e729553fa8da3babe91c6db051eda63f89

OS: Linux Mint 18.1 / Kernel 4.15.0

Java: 1.8.0_181 OpenJDK
Python: 3.7.0 (Anaconda3)

---
Building the "scrambles" dist via the command `./tmt make dist -p scrambles` yields a jar file that contains two manifests.
Both *seem to* have the same content, but my investigation so far revealed that one MANIFEST originates from GSON, only the contents themselves get overwritten by the Python zipping.
Stupidly enough, JAR files support holding two files with the exact same name under the exact same directory path. So the GSON-file gets overwritten **but retained**, and the actual manifest is added just as it's supposed.

My hot take is tmt at the following line: https://github.com/thewca/tnoodle/blob/9cabf7e729553fa8da3babe91c6db051eda63f89/tmt#L1093

Shouldn't this be `.mf` instead? At least changing it doesn't break anything obvious...

**Comment by jfly** [comment]
> Shouldn't this be .mf instead?

I think maybe we should *also* be ignoring `.mf` files, but I think we should *also* continue to remove `.sf` files.

**Comment by suushiemaniac** [comment]
Conveniently fixed this myself in #409 :innocent:
