### ISSUE TITLE
Add competitor number to FMC sheet

### ISSUE THREAD

**Issue by Baiqiang** [thewca/tnoodle#379]
Add a line for competitor to write down his number of the competition. This will improve score-taking in big FMC competition like FMC Asia.

**Comment by campos20** [comment]
I believe this can be asked apart of the rules. Including a new field on FMC sheet may cause confusion for small comps, where the competitor number in that competition is not important. Also, the regulations says [60 minutes to write a solution and your name](https://www.worldcubeassociation.org/regulations/#E2c). Would the competitor number count as name? Should they be written together?

**Comment by Baiqiang** [comment]
@campos20 Maybe we can add this as an option and allow competitor to write it down after they submitted the solution sheet.

**Comment by campos20** [comment]
> @campos20 Maybe we can add this as an option and allow competitor to write it down after they submitted the solution sheet.

That numbering if after cubecomps, which is a great tool, but not an oficial tool or related to tnoodle. It doesn't feel right including on tnoodle something that is from an outside tool. I really think we should informally ask the competitors and make sure that number is visible on a list somewhere on the venue. But my biggest competition had like 100 competitors, I can't imagine what you guys go through on a really big comp.

**Comment by jfly** [comment]
For the record, competitor numbers are now generated by the WCA website, and are exposed via WCIF (see `Person.registrantId` on https://docs.google.com/document/d/1hnzAZizTH0XyGkSYe-PxFL5xpKVWl_cvSdTzlT_kAs8/edit#, so I don't think we should be opposed to this because it's specific to some outside tool.

**Comment by campos20** [comment]
OK. I can include that after finishing #377.

**Comment by Baiqiang** [comment]
> make sure that number is visible on a list somewhere on the venue
@campos20  I don't know what's your experience. But in China and many other countries, every competitor will get a name card with their name and number on it. So it's pretty easy for competitors to write down their numbers.

**Comment by campos20** [comment]
Sorry, I forgot about that. It's a good idea, indeed, easy to code. Since I'm doing this kind of stuff, I'm volunteering to do this.

**Comment by campos20** [comment]
Fixed in https://github.com/thewca/tnoodle/pull/389
