### ISSUE TITLE
Generate output that helps restrict scramble access

### ISSUE THREAD

**Issue by lgarron** [thewca/tnoodle#382]
An easy first step:

Put all the current TNoodle output in one subfolder, and make another folder called `SEND THIS FOLDER TO THE SCRAMBLE TABLES IF YOU'RE USING COMPUTERS AT A COMPETITION` (exact name TBD), with a PDF per scramble set encrypted using the same password as the main `.zip`.

A slightly fancier approach:

> A simple strawperson would be: single page web app capable of displaying a scramble set, stores encrypted scramble with a different key for every set, Delegate has an app that allows releasing a given set. Maybe a password entry fallback on the scramble computer client-side just so that in the worst case it’s no harder to use than .zip files.
> https://worldcubeassociation.slack.com/archives/C0GHEEJ3S/p1542654595093900

**Comment by lgarron** [comment]
Also note: the problem of *releasing* access to scrambles is easy, but preventing scrambles from being accessible after is more difficult. I think we can mostly solve that issue having the web app version do a live check that the group is current, and insist on switching as soon as the Delegate marks the next round is ready.

Even better would be to integrate the round advancement into something that makes it hard to forget, such as an API that updates the projector (if the comp has one) or a screen that displays competitors to call up.

**Comment by viroulep** [comment]
Maybe just renaming folders would work just as good for a first action.
Eg: rename "pdf" to "all_scrambles_set_pdfs", and put the big pdf in a subfolder "printable_scrambles".

> A slightly fancier approach: [...]

This is indeed a bit fancy, and probably overkill for most competitions.
I like the idea of something appropriate to release only one scramble set at a time, operated only by the Delegate(s) (basically a friendly tool to safely operate the encrypted zip).

**Comment by suushiemaniac** [comment]
Please do not name the nested folder anything vaguely related to "Send" like in your OP suggestion.
Sending implies unzipping, which in turn nullifies the desired effect of the encryption

**Comment by lgarron** [comment]
> Please do not name the nested folder anything vaguely related to "Send" like in your OP suggestion.
> Sending implies unzipping, which in turn nullifies the desired effect of the encryption

In my suggestion, each PDF inside that folder is encrypted one more time (each by itself).

**Comment by bugybunny** [comment]
How is it done now? I’m not a delegate and don’t know much about it.

TNoodle generates an encrypted .zip and PDFs are just inside this archive without any subfolder or structures and the delegate needs to open the correct scrambles by just looking at the filename?

**Comment by jfly** [comment]
@bugybunny, see https://github.com/thewca/tnoodle/releases/tag/v0.14.0 for some information about how this works now.

@lgarron, I'm going to close this issue, feel free to reopen (or create a new issue) if you think there's more work to be done here.

**Comment by lgarron** [comment]
> TNoodle generates an encrypted .zip and PDFs are just inside this archive without any subfolder or structures and the delegate needs to open the correct scrambles by just looking at the filename?

Indeed. See https://www.youtube.com/watch?v=HN8O3lb-wlQ for a demo.

The PDFs use the sane file naming scheme as before. We could consider changing that, but that would require a bunch of considerations. (Feel free to file an issue for it!)
