### ISSUE TITLE
Make FM cutout sheet scrambles bigger

### ISSUE THREAD

**Issue by pedrosino** [thewca/tnoodle#394]
Here's how it looks now:
![image](https://user-images.githubusercontent.com/1881933/52602047-35fff280-2e48-11e9-957a-e7a92f462941.png)

There's almost enough space for a 9th row, but I think it would be better to make the images bigger using the height available. This would probably mean splitting the scramble sequence in two lines, but that's already the case for all other events, so not a big issue, I believe.

**Comment by campos20** [comment]
Or we could use landscape orientation and print 6 each page.

**Comment by jamesquinn1** [comment]
I like the landscape idea, as having an fmc scramble on 2 lines would bother me/presumably others.

**Comment by pedrosino** [comment]
> Or we could use landscape orientation and print 6 each page.

But then we'd have less scrambles per page and probably more wasted blank space, no?
