### ISSUE TITLE
Fix some stuff on html

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#399]
Open TNoodle and select legacy ui
Save the html to you computer
Run it against a [markup validation](https://validator.w3.org/#validate_by_upload).

You'll see that TNoodle's html have some observations to be fixed.

![Legacy](https://user-images.githubusercontent.com/10170850/54881100-1981ad80-4e2b-11e9-8140-521295865753.png)

New ui produces a similar results

![New](https://user-images.githubusercontent.com/10170850/54881104-23a3ac00-4e2b-11e9-9583-9161123b7204.png)

Since I'm labeling this a **good first issue**, I'll link a [related file](https://github.com/thewca/tnoodle/blob/master/webscrambles/WebContent/wca/scramblegen.html).

**Comment by jfenn3883** [comment]
I (hopefully) completed this task!

**Comment by jfenn3883** [comment]
That should actually fix the problem (I think).

**Comment by suushiemaniac** [comment]
Closed because legacy UI was deleted in #532
