### ISSUE TITLE
Migrate from Joda to J8 Date/Time

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#400]
Among other good new things java 8 has, we are using Joda-Time for dates, via its .jar file.
After we update to java8 and use java.time, which is the same class, as of JSR-310
We can dismiss joda-time-2.10.1.jar from /lib

**Comment by suushiemaniac** [comment]
Am I understanding you correctly in that you'd like to migrate from Joda to J8 Date/Time?

If yes, please change the title of the issue to something more concise. Right now, it sounds as if you want to migrate all of TNoodle to J8

**Comment by campos20** [comment]
@suushiemaniac before 0.15, I compiled TNoodle with java 11 and it was broke for some Windows machine. I had to compile it back with java 8. Just saying, in case that changes anything for Gradle.

**Comment by suushiemaniac** [comment]
Fixed in #453
