### ISSUE TITLE
There's a login early attempt

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#412]
Run TNoodle (0.14 or 0.15), open console. The login attempt should wait until "Log in" is clicked.

![Captura de tela de 2019-07-01 23-02-47](https://user-images.githubusercontent.com/10170850/60477106-85f32080-9c54-11e9-8f81-fd6134ca7a08.png)

**Comment by jonatanklosko** [comment]
Actually it's not a "Log in" attempt, but a check whether the user is signed in or not. If they are not signed in, then these two buttons appear, otherwise another screen is presented.

**Comment by campos20** [comment]
You are right! Thanks.
