### ISSUE TITLE
Include Unofficial warning in all but WCA-website releases

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/tnoodle#417]
Name the .zip something like `[UNOFFICIAL] CompetitionId` when the version of TNoodle used is an unofficial version distributed for testing or taken from GitHub. This will avoid confusion and ensure only the official scrambles are used (although there are also a large number of further checks along the way, there is no harm in adding another one!).

**Comment by campos20** [comment]
Sounds a great suggestion!

**Comment by campos20** [comment]
Tech: include if staging=true as well.

**Comment by campos20** [comment]
Hey @EdHollingdale, does this work for you? If so, #542 fixed this. 

![Captura de tela de 2020-03-01 14-07-00](https://user-images.githubusercontent.com/10170850/75630026-f2e4fe80-5bc5-11ea-9315-f154630f8733.png)
