### ISSUE TITLE
tnoodle jar file size is about twice as big now

### ISSUE THREAD

**Issue by alexmaasswca** [thewca/tnoodle#419]
So today I downloaded both TNoodle 14.0 and 15.0 to compare FMC scramble sheet visual differences for myself, and I noticed that 15.0 was 18.9 MB (19,921,081 bytes), whereas 14.0 was only 9.85 MB (10,336,969 bytes). Obviously 9 MB more is not really an issue, but it just seems pretty unusual for a program to double in size because of the seemingly minor updates [listed on the WCA website](https://www.worldcubeassociation.org/posts/tnoodle-0-15-0).

**Comment by campos20** [comment]
The changes listed on the website did not include technical information. Despite those were minor changes, we had a major change running on the background. 0.15 is the [first version to use Gradle](https://github.com/thewca/tnoodle/pull/409). Gradle introduced a lot of things, which explains the size difference. Before that, we used `tmt`, which is kind of a Jeremy's personal project. Using Gradle, which is a standard thing, we can build new things more easily and get help from volunteers. So, it's totally worth it!

Anyways, Gregor Billing will introduce Proguard to TNoodle, and that might resize it to about 11 mb.

Thanks for looking into this!

**Comment by jfly** [comment]
I think it's actually worth keeping this open until we've improved this. @suushiemaniac, I'm going to assign this to you =)

**Comment by suushiemaniac** [comment]
Assigning this issue implies that there is a goal which we want to achieve. What is the goal here?
- Keep the JAR under X MB --> Not feasible IMO, that way we limit ourselves to certain libraries/frameworks only.
- Keep the JAR "as small as possible" --> Who defines what's possible?
- List JAR contents? Not interesting, and indirectly already done by Gradle.

Our releases are already open-source, so everyone can figure out what's included in the JAR or which code was used to build it. If anyone has concerns about malicious code WST will be happy to prove them wrong, and on a broader scale I find it wrong to distribute Webserver JARs to Delegates anyways.

**Comment by jfly** [comment]
We have always had a policy of making "some nonzero effort" to keep the final artifact small. TNoodle is a pretty old project so the thinking here may be dated, and the thinking wasn't always documented. Some ideas: Keeping the jar small is nice for emergency edge scenarios where you're at a competition (possibly with very poor internet) and have to download a jar file to generate a scramble last minute. Some delegates may even be on internet/phone plans where data is limited or expensive. @lgarron for more thoughts. 

I'm not saying this is worth a lot of effort, but if it's easy to throw proguard into the Gradle configuration, and it has a measurable impact on end file size, that feels like a win to me.

@suushiemaniac, feel free to unassign yourself if you're not interested in working on this! It would be nice to have your purely technical thoughts on if there would be any technical obstacles to introducing proguard to our gradle configuration, though.

**Comment by suushiemaniac** [comment]
ProGuard was introduced in https://github.com/thewca/tnoodle/pull/421, so once we build a new release the JAR size should not increase anymore.
