### ISSUE TITLE
Show raised clock pins in drawings

### ISSUE THREAD

**Issue by lgarron** [thewca/tnoodle#423]
There have been recent clock pin issues, including some scrambles with completely inverted pins. It would be nice to improve the way we show pins that are up by extending them in the drawings:

![Clock Round 1](https://user-images.githubusercontent.com/248078/63018132-f644b280-be4c-11e9-85f4-8ae45e2744a3.png)

**Comment by pedrosino** [comment]
I like it!

**Comment by suushiemaniac** [comment]
@lgarron Do you have the SVG at hand that was used to generate the sample image? Then it would be quite a trivial change imo…

**Comment by lgarron** [comment]
Unfortunately, that's a PNG mockup!

**Comment by pedrosino** [comment]
Not sure when/if I'll be able to look into this, but here is something interesting I found:

drawPin function is at https://github.com/jsgao0/Cylinder/blob/master/jquery.cylinder.js
It just draws a circle and paints with the PinUp or PinDown color.

Here's some jquery to make a cylinder: https://github.com/jsgao0/Cylinder/blob/master/jquery.cylinder.js 
Sample output: http://jsbin.com/pemivaw/17/edit?html,output

One idea that just occurred to me was to draw two circles for the pin that's up. Draw the regular one then draw another one some pixels above. Sort of a hack, but could look similar to what Lucas showed.

**Comment by jfly** [comment]
@pedrosino, FYI, the image drawing code in TNoodle is written in java, not javascript.

**Comment by pedrosino** [comment]
> @pedrosino, FYI, the image drawing code in TNoodle is written in java, not javascript.

Oh, I know :)
It was just something I found which can maybe be adapted to Java, if we need.
