### ISSUE TITLE
Translate Registrant ID

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#424]
https://github.com/thewca/tnoodle/pull/389 introduced a new expression to translate: `Registrant ID`. This registrant ID is the number the competitor receive in that competition. So, for FMC, competitor can fill Registrant ID and whoever is in charge of results input can use that number on cubecomps. This will be useful in large competitions.

Status

- [x] da
- [x] de
- [x] en
- [x] es
- [x] et
- [x] fi
- [x] fr
- [x] hr
- [x] hu
- [x] id
- [x] it
- [x] ja
- [x] ko
- [x] nb
- [x] pl
- [x] pt-BR
- [x] pt
- [x] ro
- [x] ru
- [x] sl
- [x] vi
- [x] zh-CN
- [x] zh-TW

**Comment by Laura-O** [comment]
Commenting here as I do not want to re-open the other issue: will there be a version with and without registrant ID?
I'd definitely prefer to have a version *without* the Registrant ID as I am sure this will only be used at a small minority in my region and will mainly cause confusion among the competitors.

**Comment by campos20** [comment]
> Commenting here as I do not want to re-open the other issue: will there be a version with and without registrant ID?

Well, it's not on the plans right now. Perhaps this could be left unfilled. I think generating files with and without some features could also lead to mistakes on organizers side.
 
> Edit: And the most suitable German translation is `Teilnehmer ID`

Thanks!

**Comment by cubizh** [comment]
For "pt", the correct expression to use is `ID de registo`

**Comment by hanwu85** [comment]
I have [PR](https://github.com/thewca/tnoodle/pull/429) the zh-TW one.  But the travis check failed, could someone confirm if it's a real fail or a incorrect fail?
Thanks!

**Comment by viroulep** [comment]
That's a real fail because your PR only brings in the zh-TW translation, where they should be brought altogether at the same time :)
We have #426 to bring all the translations in the same PR.

@campos20 could you please take the zh-TW translation from #429 and add it to #426?

**Comment by campos20** [comment]
It is expected that Travis fails until all the the translations are ready.

> We have #426 to bring all the translations in the same PR.

I'm considering accepting PRs then fixing the history later.

**Comment by viroulep** [comment]
What do you mean by "fixing the history"?

**Comment by campos20** [comment]
> What do you mean by "fixing the history"?

Squash/rebase

**Comment by viroulep** [comment]
Merged pull requests land in a public branch; as a consequence any operation rewriting history (such as rebase or squash) is not an option (you can read more about why it is such a bad idea [here](https://www.atlassian.com/git/tutorials/merging-vs-rebasing).
I think the tnoodle master branch is protected against non-forward push anyway :) 

This is why I'd rather have created a single PR where we are free to edit the history in any way we want (and making sure tests look good before merging the pr).

**Comment by campos20** [comment]
> Merged pull requests land in a public branch; as a consequence any operation rewriting history (such as rebase or squash) is not an option (you can read more about why it is such a bad idea [here](https://www.atlassian.com/git/tutorials/merging-vs-rebasing).
> I think the tnoodle master branch is protected against non-forward push anyway :)
> 
> This is why I'd rather have created a single PR where we are free to edit the history in any way we want (and making sure tests look good before merging the pr).

Thanks for pointing that out! I know it was a bad idea in big teams with a lot of commits, but this also make sense. I'm going to concentrate all the translation on #426 from now on :D

**Comment by campos20** [comment]
I just sent a ping email.

**Comment by campos20** [comment]
Sebastiano Tronto translated to it

**Comment by suushiemaniac** [comment]
Closing this issue as the [relevant PR](https://github.com/thewca/tnoodle/pull/426) has been merged
