### ISSUE TITLE
Do not show Scramble Set A if there is just one set

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#433]
This is mostly for FMC, which is visible for the competitor. Removing that would lead to a cleaner view. Anyways, scrambles that scrambling person see might use that as well.

![image](https://user-images.githubusercontent.com/10170850/68070226-69720c80-fd4a-11e9-993a-74a41f4d704b.png)

![image](https://user-images.githubusercontent.com/10170850/68070239-b1912f00-fd4a-11e9-97af-dafc8507c6d4.png)

**Comment by suushiemaniac** [comment]
Resolved by https://github.com/thewca/tnoodle/pull/578

woop woop first contribution by @Shadowjockey :tada:
