### ISSUE TITLE
use in Flutter

### ISSUE THREAD

**Issue by LXD312569496** [thewca/tnoodle#449]
how can i use it in Flutter？to get scramble

**Comment by suushiemaniac** [comment]
Hello,

Flutter is a framework for building mobile app interfaces. You will have to define a text field and fill it with content from TNoodle.

To get a scramble string, instantiate any subclass of [`Puzzle.java`](https://github.com/thewca/tnoodle/blob/master/scrambles/src/main/java/net/gnehzr/tnoodle/scrambles/) and invoke the [`generateScrambles`](https://github.com/thewca/tnoodle/blob/master/scrambles/src/main/java/net/gnehzr/tnoodle/scrambles/Puzzle.java#L125) method.

A list of all available WCA puzzles can be found at [`PuzzlePlugins.kt`](https://github.com/thewca/tnoodle/blob/master/scrambles/src/main/kotlin/net/gnehzr/tnoodle/plugins/PuzzlePlugins.kt)

Please also note, that this is not an FAQ forum nor any documentation. You are normally supposed to report issues where the software is broken or behaves unexpectedly.

Have fun building your app!
- Gregor

**Comment by LXD312569496** [comment]
how I use in Flutter ，ios platform

**Comment by suushiemaniac** [comment]
Please see the quote from my original response:

> Flutter is a framework for building mobile app interfaces. You will have to define a text field and fill it with content from TNoodle.
> To get a scramble string, instantiate any subclass of Puzzle.java and invoke the generateScrambles method.
> A list of all available WCA puzzles can be found at PuzzlePlugins.kt

I do not have any experience with Flutter, so I cannot give you an example.
