### ISSUE TITLE
Scenario to download zip with incorrect competition name

### ISSUE THREAD

**Issue by Goosly** [thewca/tnoodle#563]
## Actual (problem) behavior
It's quite easy to download the zip with an incorrect competition name,

## Expected behavior
The zip always has the correct competition name.

## Steps To Reproduce
1. Make sure you have at least 2 competitions. Open TNoodle in your browser.
2. Navigate to one competition. Click "generate scrambles".
3. While the scrambles are generating, navigate to your second competition.
4. Wait for generating to be done, then click "download"

## Desktop (please complete the following information):
Windows, Chrome, TNoodle 1.0.0

## Screenshots [OPTIONAL]
I generated scrambles for the euro championship, but after navigating to my template competition, the zip has the name of the template competition, while it contains scrambles for the euro championship.
![image](https://user-images.githubusercontent.com/12575384/81921407-dfe5a600-95da-11ea-8738-e6cbeb013aad.png)

**Comment by suushiemaniac** [comment]
Hey Manu, thanks for reporting! Just to make sure, the scrambles inside the "wrongly named ZIP" should be watermarked as "WCA European Championship" (ie the competition you originally selected). Correct?

**Comment by Goosly** [comment]
Yes, the content of the Zip file is correct. Only the name is incorrect.

**Comment by campos20** [comment]
Fixed
