### ISSUE TITLE
Incorrect spacing in the title of FMC sheets 

### ISSUE THREAD

**Issue by mirandapedro** [thewca/tnoodle#565]
## Actual behavior

The title of FMC sheets doesn't have enough space between the lines of the name of the competition and the description of the attempt. The two lines visually conflict with each other.

## Expected behavior

The line of the description of the attempt should be lower in order not to touch the title of the competition.

## Steps To Reproduce
1. Launch TNoodle;
2. Generate an FMC scramble set;
3. Open the generated FMC scramble set (the one that has the scrambles in it); 
4. Look in the top right hand corner of the page.

## Desktop:
 - OS: Windows 10;
 - Browser: Chrome 81.0.4044.138;
 - TNoodle Version: 1.0;
- Java version: Java 8, update 131.

## Screenshots 

[Screenshot of the bug](https://imgur.com/D1rEDfn)

**Comment by campos20** [comment]
@mirandapedro could you please include a screenshot?

**Comment by mirandapedro** [comment]
It's on the link on the original post (or (here)[https://m.imgur.com/D1rEDfn]).

I don't how to post the image here on GitHub, though 😅.

**Comment by campos20** [comment]
> It's on the link on the original post (or [here](https://m.imgur.com/D1rEDfn)).
> 
> I don't how to post the image here on GitHub, though .

Drag and drop should work :)

**Comment by campos20** [comment]
This one should be pretty quick and I'm linking relevant code. We use a function to display blocks of texts fitting width and height. Texts are added to a list and then it's rendered. One quick solution would be [add an empty phrase between the lines](https://github.com/thewca/tnoodle/blob/6ccc25c0bcbd44e2bc90897ad0be0c6afe51f57b/webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/FmcSolutionSheet.kt#L168). A better solution would be increase the `leadingMultiplier`. The method `populateRect` does not use it nowadays.

**Comment by campos20** [comment]
@mirandapedro this' been fixed. Merging if you agree

![image](https://user-images.githubusercontent.com/10170850/83311164-c51f4e00-a1e4-11ea-862b-9fedb5424dd7.png)

**Comment by mirandapedro** [comment]
Looks good!! Go ahead with merging.

Thanks for fixing this!
