### ISSUE TITLE
Improve UI colo(u)rs

### ISSUE THREAD

**Issue by suushiemaniac** [thewca/tnoodle#584]
partial copy/paste from an email by Manu on the release testing thread:

> 1. The buttons all have very different colours (black, blue, green, blue-green-ish, white). I think a bit more consistency would make the interface more intuitive.
> 2. Related to 1, a disabled "Generate Scrambles" button is almost the same blue as the enabled one, and it's not clear that it is disabled, nor why. If I click on it, nothing happens! Only when I'm a very patient user and hover my cursor over it, without clicking, the error appears. (Of course in this case the problem should be obvious for experienced delegates, still it might be confusing for less experienced ones.)

**Comment by suushiemaniac** [comment]
In an effort to push forward the release, could you please add your thoughts here and/or report any progress? @campos20

**Comment by campos20** [comment]
![image](https://user-images.githubusercontent.com/10170850/86521278-f5ca5700-be24-11ea-8ec7-8ad8fb32c217.png)

![image](https://user-images.githubusercontent.com/10170850/86521285-04187300-be25-11ea-9c35-0f3724d8c21b.png)

I replaced some colors by the same blue.

Also, now it's just showing Manual Selection if necessary

![image](https://user-images.githubusercontent.com/10170850/86521295-2e6a3080-be25-11ea-9ec7-ccad2d2889c9.png)

**Comment by campos20** [comment]
About the scramble button, I'd really like to keep as is. That disabled behavior/colors is somehow default and letting the mouse hover is what is expected to get help, which appears in less than 1 second.

**Comment by suushiemaniac** [comment]
closed as per #585
