### ISSUE TITLE
Clicking on "Translations" triggers "Generate scrambles"/"Download scrambles"

### ISSUE THREAD

**Issue by zeecho** [thewca/tnoodle#599]
## Actual (problem) behavior
When I clicked on the Fewest Moves' translations button, it automatically triggered "Generate scrambles". Then, every time I clicked on the "Translations" button, it triggered the download action again.

## Expected behavior
Allow to select FM translations without triggering the generate/download action.

## Steps To Reproduce
1. Click on "Translations" in the Fewest Moves section
2. See that "Generate scrambles" has been triggered
3. Click on "Translations" in the Fewest Moves section
4. See that "Download scrambles" has been triggered
5. Click on "Translations" in the Fewest Moves section
6. See that "Download scrambles" has been triggered again

## Desktop:
 - OS: Arch Linux
 - Browser: Firefox 79.0 
 - TNoodle Version 1.0.1
- Java version: Java 8 (1.8.0_262)

**Comment by suushiemaniac** [comment]
Confirmed and reproduced under Manjaro / Chrome 84 / JRE 11.0.8

Thank you for reporting, we will work on a fix!

**Comment by campos20** [comment]
Many thanks for reporting!

Fixed by #601
