### ISSUE TITLE
After extracting the zip file, every pdf has no rights (Linux)

### ISSUE THREAD

**Issue by zeecho** [thewca/tnoodle#600]
## Actual (problem) behavior
After extracting the zip file, every pdf files had 000 rights (`----------`) instead of something like 644 (`-rw-r--r--`). This means the files could not be opened until I fixed the rights.

## Expected behavior
I'm expected to have the rights to open the files right after extracting them.

## Steps To Reproduce
1. `unzip` the scrambles zip
2. `cd` on the extracted folder
3. check the rights with `ls -l` for instance
4. try to open it (if the rights where `----------` it should not work until you do `chmod 644` on the file)

## Desktop (please complete the following information):
 - OS: Arch Linux
 - Browser: Firefox 79.0
 - TNoodle Version 1.0.1
- Java version: Java 8 (1.8.0_262)

## Additional context
- Tried on a Debian computer as well and I could not reproduce this 
- Tried on my computer with an old Tnoodle zip and it worked fine so it does seem to come from the new version

**Comment by suushiemaniac** [comment]
Fixed as per #602. Will be included in an upcoming `1.0.2` release!
