### ISSUE TITLE
FM Translation Bug

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/tnoodle#611]
## All translations included
When selecting only one translation, I get all of them. 

## Expected behavior
I should only get the translations I selected

## Steps To Reproduce
1. Select FM as an event
2. Press translations
3. Press 'select none'
4. Select Danish
5. Open the file
6. Go to 'printing'
7. Go to 'Fewest Moves - additional files'
8. go to 'translations'. There are all translations.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Chrome 85
 - TNoodle Version 0.15.1
- Java version Java 8

## Additional 
Clicking the 'Translations' box under FM also acts the same way as the "Generate scrambles" and "download scrambles" button.

**Comment by suushiemaniac** [comment]
Hey Daniel, thank you for reporting! I kinda doubt that you're using TNoodle 0.15.1 as it does not have selectable FMC translations as a feature :P But Alexandre and I already became aware of this bug in TNoodle 1.0.1.

We have fixed it in https://github.com/thewca/tnoodle/pull/606 and I am discussing with WRC and WST how to proceed with the release.

**Comment by DanielEgdal** [comment]
Cool. I thought you were still waiting for me to open this, but great that you already found a solution. :) 
And right, I forgot to update that point of the template.
