### ISSUE TITLE
Freeze navigation while generating scrambles

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#624]
## Is your feature request related to a problem? Please describe.
Log in (you may use query parameter `staging=true`) and ask for scramble generation.

![image](https://user-images.githubusercontent.com/10170850/94867552-d63ccd80-0417-11eb-9b12-cb8c0d566210.png)

If you navigate away (e.g. for Manual Selection), you'll see just some bars.

![image](https://user-images.githubusercontent.com/10170850/94867693-169c4b80-0418-11eb-8084-d0581f25acac.png)

## Describe the solution you'd like
Freeze navigation (user can't click competitions or manual until the process is done).

## Describe alternatives you've considered
As an alternative, Scramble Button could be a progress bar itself and if user navigates, progress is shown just on Scramble Button.

## Additional context [OPTIONAL]
* Open TNoodle
* add `?staging=true` to the URL.
* Hit Log In
* Pass some [delegate's id](https://www.worldcubeassociation.org/delegates) (or you can use mine, 2015CAMP17)
* Back to tnoodle, add choose a competition (if the user you selected has no upcoming competition, you can force one by adding a query `competitionId`, like `http://localhost:3000/scramble?staging=true&competitionId=AustralianNationals2020`)
* Generate and navigate

If you choose freezing navigation, this won't be needed anymore.

https://github.com/thewca/tnoodle/blob/d44cb840fbdc40018ac845f9a4daa9a4358d866e/tnoodle-ui/src/main/components/Main.jsx#L65

Also, it would be nice freezing copies, FMC buttons, MBLD cube and any other interactive field.

**Comment by shzcuber** [comment]
I'm on it

**Comment by shzcuber** [comment]
Hello,

I froze the fmc buttons, mbld button, copies, and sidebar buttons. I pushed my changes on the branch feature/change-title (I realized that I should've made a new branch only after I did my changes). Please let me know if I need to do anything more. Thanks.

**Comment by campos20** [comment]
Fixed by #632
