### ISSUE TITLE
How to verify the scramble is proper?

### ISSUE THREAD

**Issue by AK51** [thewca/tnoodle#630]
I am a CS students and I wonder for each scramble, which part of the code take care of the checking that the scramble is not too easy to solve? Does the code check number of moves using CFOP and ROUX?
Thanks

**Comment by AK51** [comment]
Hi, it seems the scramble is done in the server instead of in tnoodle, may I know if the server code project is the open source? Thx

**Comment by campos20** [comment]
> Hi, it seems the scramble is done in the server instead of in tnoodle, may I know if the server code project is the open source? Thx

This is where the scrambles are generated

https://github.com/thewca/tnoodle-lib



> I am a CS students and I wonder for each scramble, which part of the code take care of the checking that the scramble is not too easy to solve? Does the code check number of moves using CFOP and ROUX?
> Thanks

This is the variable you are looking for

https://github.com/thewca/tnoodle-lib/blob/dba4a386460c9d19cb8bc43015b6b5f3caed6030/scrambles/src/main/java/org/worldcubeassociation/tnoodle/scrambles/Puzzle.java#L41

It does not use CFOP neither Roux.

**Comment by campos20** [comment]
I'm closing this as not really an issue. Feel free to reach us via email for further discussions in software@worldcubeassociation.org
