### ISSUE TITLE
1.1.0 crash

### ISSUE THREAD

**Issue by lz1998** [thewca/tnoodle#664]
Running `java -jar TNoodle-WCA-1.1.0.jar` will cause crash.

I found`offlineHandler.setApplicationIcon(isWrapped)` in `WebscramblesServer.kt` will cause crash on MacOS Big Sur

```shell
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Detected os: Mac OS X
needsReExecing: false
2021-04-21 20:07:00.994 java[12232:2503683] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2077a6af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff204b23c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff207a2a9a -[NSException raise] + 9
	3   AppKit                              0x00007fff22f49460 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22f34121 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1375
	5   AppKit                              0x00007fff22f33bbb -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   AppKit                              0x00007fff23687834 -[NSStatusBarWindow initForStatusItem:] + 101
	7   AppKit                              0x00007fff2368a5a4 -[NSStatusItem _initWithStatusBar:length:priority:systemInsertOrder:] + 316
	8   AppKit                              0x00007fff231d4329 -[NSStatusBar _statusItemWithLength:withPriority:] + 76
	9   jna5804632215916950629.tmp          0x00000001352a311a ffi_prep_go_closure + 1354
	10  ???                                 0x0000700009606b18 0x0 + 123145459624728
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by lz1998** [comment]
`SystemTray.get()`
https://github.com/thewca/tnoodle/blob/master/webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/server/OfflineJarUtils.kt#L46

**Comment by campos20** [comment]
@suushiemaniac can you look into this, please?

It's the second feedback we receive about mac. Maybe it would be worth it to add a travis configuration for [that environment](https://docs.travis-ci.com/user/tutorial/#selecting-a-different-programming-language).

**Comment by suushiemaniac** [comment]
Thank you for reporting this issue! In order to help with debugging, could you provide the full logging output of TNoodle?

There should be a file called `tnoodle.log` in the same folder where the TNoodle JAR is stored. If possible, please attach it to this issue.

**Comment by lz1998** [comment]
> Thank you for reporting this issue! In order to help with debugging, could you provide the full logging output of TNoodle?
> 
> There should be a file called `tnoodle.log` in the same folder where the TNoodle JAR is stored. If possible, please attach it to this issue.

`SystemTray.get()` will cause crash on MacOS Big Sur.

Remove it to solve this problem

**Comment by suushiemaniac** [comment]
We cannot simply remove this call, because we need it to display a TNoodle icon in the system tray to make the user aware that the app is running.

I'll check with the maintainer of the library to see whether this is a known issue with an existing solution or workaround.
