### ISSUE TITLE
Title for FMC cutout sheets is confusing

### ISSUE THREAD

**Issue by timreyn** [thewca/tnoodle#675]
## Actual (problem) behavior
The attempt title is something like

"Fewest Moves Round 1 Attempt 2 Scramble 1 of 3"

I'm not sure what "Scramble 1 of 3" means -- typically a single Fewest Moves attempt only has one scramble.  At Back to Cambridge many competitors were confused and thought they had the scramble for attempt 1.

## Expected behavior
Drop the scramble suffix, and just have the text be "Fewest Moves Round 1 Attempt 2"

Relevant code: https://github.com/thewca/tnoodle/blob/master/webscrambles/src/main/kotlin/org/worldcubeassociation/tnoodle/server/webscrambles/pdf/FmcScrambleCutoutSheet.kt#L42-L48

**Comment by gregorbg** [comment]
Hey Tim, thanks for the report! This is one of the first occasions where we're observing the new TNoodle backend being used in practice, so I appreciate you telling us about this right away.

From what I can tell, `Back to Cambridge` had a Fewest Moves Mo3, which is what the "Scramble 1 of 3" is referring to.
But indeed it's a bug that the counter did not increment properly, I'll get to fix it straight away!

**Comment by timreyn** [comment]
Thanks!  Would it then say "Fewest Moves Round 1 Attempt 2 Scramble 2 of 3"?  It should probably only say one of the two -- either "attempt 2" or "scramble 2".

**Comment by gregorbg** [comment]
No, that would be quite redundant. I've opted for "Scramble X of 3" in #676, see attached ZIP
[[UNOFFICIAL] Back to Cambridge B 2021.zip](https://github.com/thewca/tnoodle/files/6722305/UNOFFICIAL.Back.to.Cambridge.B.2021.1.zip)

**Comment by timreyn** [comment]
Awesome, thank you!

**Comment by gregorbg** [comment]
Fixed as per #676, will be part of a release soon:tm: 
There have been reports about incompatibilities with the newest macOS version so we will probably build a new release in the next 14 days.
