### ISSUE TITLE
Error response when generating scrambles with two groups of 3x3x3 Multiblindfolded

### ISSUE THREAD

**Issue by poiuytre121** [thewca/tnoodle#680]
## Actual (problem) behavior
During scramble generation for Brizzon Side Open 2021 error occured which prevented scramble generation. After changing 3x3x3 MBLD to one group (initially it was at 2 groups) scrambles were generated without any issues. Screenshot of the error below:
<img width="1680" alt="Zrzut ekranu 2021-07-16 o 01 58 18" src="https://user-images.githubusercontent.com/20459662/125873049-79de05f4-6c55-43b9-b7e5-e8671011aff4.png">

## Expected behavior
Scrambles should be generating for competition with two groups of 3x3x3 MBLD

## Steps To Reproduce
1. Launch TNoodle
2. Log in
3. Select competition with groups of 3x3x3 MBLD
4. Click "Generate Scrambles"
5. See error

## Desktop (please complete the following information):
 - OS: macOS 11.2
 - Browser Chrome 91.0.4472.114 
 - TNoodle Version 1.1.1
- Java version 8 update 192

## Additional context [OPTIONAL]
I've tried refreshing the page, finally went around the problem and generated second set separately.

**Comment by campos20** [comment]
Did you try updating schedule/events before generating again?

https://www.worldcubeassociation.org/competitions/BrizZonSideOpen2021/events/edit

**Comment by poiuytre121** [comment]
I had one group at first, before trying to generate I noticed that and changed it on the website to two groups, tried to generate, got error, went back to the website, set it back to 1 group, generated successfully and decided to report error and get to printing as I had little time before I had to go out.

**Comment by gregorbg** [comment]
Hey Przemysław, thanks for reporting this issue! I think I have a vague idea what's going on here, because having more than 1 group in MBLD is an edge case that is currently not covered by the specifications very well.

I will investigate some time later this week.
