### ISSUE TITLE
Spaces in the url of the competition website

### ISSUE THREAD

**Issue by Nanush7** [thewca/tnoodle#687]
## Actual (problem) behavior
When you use the link to view and change rounds, the url has spaces in the competition name. For example: https://www.worldcubeassociation.org/competitions/Montevideo%20ReOpen%202021/events/edit
404 is displayed:

![Captura](https://user-images.githubusercontent.com/59543882/133853275-2b222b73-3ec5-49e4-9948-20648bfdafbc.JPG)

## Expected behavior
The url should be:
https://www.worldcubeassociation.org/competitions/MontevideoReOpen2021/events/edit
This url is the one that leads to the right place.

## Steps To Reproduce
1. Open TNoodle.
2. Log In and choose a competition.
3. Click on the link "the WCA" (the one you can see in the image below).
4. See error.

![Captura2](https://user-images.githubusercontent.com/59543882/133854226-515b7fbd-f7db-4b45-a359-1172ff11add3.JPG)

## Desktop:
 - OS: Windows 10
 - Browser: Firefox 92.0
 - TNoodle Version: 1.1.1
- Java version: Java 8

**Comment by gregorbg** [comment]
Thank you for reporting this issue! It was due to a simple human error during programming, sorry we didn't notice it before...

**Comment by Nanush7** [comment]
> Thank you for reporting this issue! It was due to a simple human error during programming, sorry we didn't notice it before...

No problem! It's just a detail.
