### ISSUE TITLE
Can the same scramble be generated twice in the same round?

### ISSUE THREAD

**Issue by timreyn** [thewca/tnoodle#762]
I'm not familiar enough with TNoodle code these days to answer this myself, but it came up in a discussion at NA Champs:

The probability of getting two of the same scrambles in the same 2x2 group (ignoring extras) is approximately 1 - 1/367416. In 2019 there were 5928 2x2 scramble sets generated, which means the probability per (normal, non-COVID-affected) year of this happening is about 1/60. Pyraminx, ignoring tips, is about 1/20 per year.

Is there any protection against this in TNoodle? If not, it might be worth adding.

**Comment by timreyn** [comment]
Thanks @gregorbg !

**Comment by Jambrose777** [comment]
Uninformed question regarding this:
Is the same filtering done within MBLD scrambles?

**Comment by gregorbg** [comment]
Yes!
