### ISSUE TITLE
The latest version error in v1.1.3

### ISSUE THREAD

**Issue by Dhruvacube** [thewca/tnoodle#779]
## Actual (problem) behavior
![image](https://user-images.githubusercontent.com/34207400/189042598-78652dd2-b354-4a4e-99e1-4424f236fe1c.png)

when downloading the latest ver from above said error msg it downloads the 1.1.2 ver

## Expected behavior
The error message should not be shown

## Steps To Reproduce
1. Go to 'https://github.com/thewca/tnoodle/releases/tag/v1.1.3'
2. download the jar file
3. Run the jar file

## Desktop (please complete the following information):
 - OS: Windows 10 Pro
 - Browser: Chrome Version 105.0.5195.52 (Official Build) (64-bit)
 - TNoodle Version: TNoodle-WCA-1.1.3
- openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment Temurin-11.0.16+8 (build 11.0.16+8)
OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (build 11.0.16+8, mixed mode)

**Comment by gregorbg** [comment]
Hello,

TNoodle 1.1.3 has not yet been approved by WST and WRC for use in competitions.
The official TNoodle release that is ready to use in competition can always be obtained at https://www.worldcubeassociation.org/regulations/scrambles/
