### ISSUE TITLE
MBLD Not able to generate scrambles for multiple groups

### ISSUE THREAD

**Issue by Jambrose777** [thewca/tnoodle#798]
## Actual (problem) behavior
I have 2 groups for multi-blind and have set the scramble sets in WCA to be 2. Tnoodle autofills with 1 and does not allow me to change it.

## Expected behavior
Tnoodle Should generate 2 groups.
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/11577241/205959077-4bfba5e0-0126-4724-ab3c-f043f14dff9d.png">

## Additional context [OPTIONAL]
I used the legacy UI to generate the second set, but this would still be nice to automatically have the correct number.

**Comment by campos20** [comment]
This looks correct. When TNoodle disables the information, it means that it came from the WCA API. I'm assuming that this is for GACubersPersonalBestQuest2022, which is your next competition. It is listed as 1 scramble set in the WCA website.

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/10170850/206322608-4f5b6f9e-46b7-492b-9c36-c6787697ea82.png">

Please update it there and refresh your TNoodle page.

**Comment by Jambrose777** [comment]
Weird, in my screenshot it has the sets = 2. I wonder if it got overwritten by groupifier? Regardless, certainly closing this as user error.
